package main

import (
	"fmt"
	"go/format"
	"go/types"
	"strings"
	"unicode"

	. "github.com/dave/jennifer/jen"
)

const (
	pkgCfg   = "github.com/USA-RedDragon/configulator/v2"
	pkgPFlag = "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	pfl      = "github.com/spf13/pflag"
)

func lowerFirst(s string) string {
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

type emitter struct {
	m            *Model
	f            *File
	shadows      map[string]bool // shadow name -> emitted (guard)
	shadowOrder  []string        // emission order, for the fast paths
	shadowFields map[string][]*Field
	needQuoteKey bool
}

// quoteKeyName names the per-file quoting helper for map-key path
// segments. Inlined into generated output rather than exported from the
// runtime: it is formatting plumbing, not policy.
func (e *emitter) quoteKeyName() string {
	e.needQuoteKey = true
	return lowerFirst(e.m.TypeName) + "QuoteKey"
}

func emit(m *Model, flagsMode string) ([]byte, error) {
	outPkgPath = m.PkgPath
	e := &emitter{
		m: m, f: NewFile(m.PkgName),
		shadows:      map[string]bool{},
		shadowFields: map[string][]*Field{},
	}
	e.f.HeaderComment("Code generated by configulator. DO NOT EDIT.")
	e.f.HeaderComment("")
	e.f.HeaderComment("//go:build goexperiment.jsonv2")
	e.f.ImportName(pkgCfg, "configulator")
	e.f.ImportAlias(pkgCfg, "configulator")
	e.f.ImportAlias(pkgPFlag, "cpflag")
	e.f.ImportName(pfl, "pflag")

	e.emitShadowStruct(shadowName(m.TypeName), m.Fields)
	e.emitSchemaCtor(flagsMode)
	e.emitApplyDefaults()
	e.emitDecodeFile()
	e.emitApplyTo(shadowName(m.TypeName), m.Fields, "", "cfg")
	e.emitApplyEnv()
	switch flagsMode {
	case "pflag":
		e.emitPFlagHooks()
	case "std":
		e.emitStdFlagHooks()
	}
	e.emitFastPaths()
	e.emitPrintConfig()
	if e.needQuoteKey {
		e.f.Comment("// " + e.quoteKeyName() + " quotes a map key whose characters would make")
		e.f.Comment("// a dotted origin path ambiguous.")
		e.f.Func().Id(e.quoteKeyName()).Params(Id("k").String()).String().Block(
			For(List(Id("_"), Id("c")).Op(":=").Range().Id("k")).Block(
				If(Id("c").Op("==").LitRune('.').Op("||").Id("c").Op("==").LitRune('[')).Block(
					Return(Lit(`"`).Op("+").Id("k").Op("+").Lit(`"`)),
				),
			),
			Return(Id("k")),
		)
	}

	src := []byte(fmt.Sprintf("%#v", e.f))
	return format.Source(src)
}

func shadowName(typeName string) string { return lowerFirst(typeName) + "Shadow" }

func (e *emitter) shadowFor(t types.Type) string {
	named, ok := t.(*types.Named)
	if !ok {
		panic("shadowFor: not a named type")
	}
	return shadowName(named.Obj().Name())
}

// outPkgPath is set once per emit() so type rendering can suppress
// self-imports for types defined in the output package.
func goName(f *Field) string {
	parts := strings.Split(f.GoName, ".")
	return parts[len(parts)-1]
}

// cfgSel renders cfg.<GoName possibly promoted>.
func cfgSel(recv string, f *Field, extra ...string) *Statement {
	s := Id(recv)
	for _, p := range strings.Split(f.GoName, ".") {
		s = s.Dot(p)
	}
	for _, p := range extra {
		s = s.Dot(p)
	}
	return s
}

func (e *emitter) emitSchemaCtor(flagsMode string) {
	n := e.m.TypeName
	d := Dict{
		Id("ApplyDefaults"): Id(lowerFirst(n) + "ApplyDefaults"),
		Id("DecodeFile"):    Id(lowerFirst(n) + "DecodeFile"),
		Id("ApplyEnv"):      Id(lowerFirst(n) + "ApplyEnv"),
	}
	if req := requiredPaths(e.m.Fields, ""); len(req) > 0 {
		var lits []Code
		for _, p := range req {
			lits = append(lits, Lit(p))
		}
		d[Id("Required")] = Index().String().Values(lits...)
	}
	e.f.Comment(fmt.Sprintf("%sSchema returns the generated schema for %s.", n, n))
	e.f.Func().Id(n+"Schema").Params().Op("*").Qual(pkgCfg, "Schema").Index(Id(n)).Block(
		Return(Op("&").Qual(pkgCfg, "Schema").Index(Id(n)).Values(d)),
	)
}

// requiredPaths collects dotted paths of required:"true" fields.
func requiredPaths(fields []*Field, prefix string) []string {
	var out []string
	for _, f := range fields {
		p := joinPath(prefix, f.Tag)
		if f.Required {
			out = append(out, p)
		}
		if f.Kind == KindStruct {
			out = append(out, requiredPaths(f.Fields, p)...)
		}
	}
	return out
}
