package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"strings"
	"unicode"

	. "github.com/dave/jennifer/jen"
	"golang.org/x/tools/imports"
)

const (
	flagsPFlag = "pflag"
	flagsStd   = "std"
	flagsNone  = "none"
)

const (
	pkgCfg   = "github.com/USA-RedDragon/configulator/v2"
	pkgImpl  = "github.com/USA-RedDragon/configulator/v2/impl"
	pkgPFlag = "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	pfl      = "github.com/spf13/pflag"
)

func lowerFirst(s string) string {
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

type emitter struct {
	m            *Model
	f            *File
	shadows      map[string]bool // shadow name -> already emitted
	shadowOrder  []string        // emission order, for the fast paths
	shadowFields map[string][]*Field
	needQuoteKey bool
}

// quoteKeyName returns the name of the helper that quotes map keys in
// origin paths. The helper is written into each generated file instead of
// being exported from the runtime, since it's only formatting.
func (e *emitter) quoteKeyName() string {
	e.needQuoteKey = true
	return lowerFirst(e.m.TypeName) + "QuoteKey"
}

func emit(m *Model, flagsMode string) ([]byte, error) {
	switch flagsMode {
	case flagsPFlag:
		if err := checkFlagTags(flagFields(m.Fields, pflagOK)); err != nil {
			return nil, err
		}
	case flagsStd:
		if err := checkFlagTags(flagFields(m.Fields, stdOK)); err != nil {
			return nil, err
		}
	}
	e := &emitter{
		m: m, f: NewFilePathName(m.PkgPath, m.PkgName),
		shadows:      map[string]bool{},
		shadowFields: map[string][]*Field{},
	}
	e.f.HeaderComment("Code generated by configulator. DO NOT EDIT.")
	e.f.HeaderComment("")
	e.f.HeaderComment("//go:build goexperiment.jsonv2")
	e.f.ImportName(pkgCfg, "configulator")
	e.f.ImportName(pkgImpl, "impl")
	e.f.ImportAlias(pkgPFlag, "cpflag")
	e.f.ImportAlias(pkgStdFlag, "cstd")
	e.f.ImportName(pfl, "pflag")
	e.f.ImportName(pkgJSONText, "jsontext")
	e.f.ImportName(pkgJSONv2, "json")

	e.emitShadowStruct(shadowName(m.TypeName), m.Fields)
	e.emitSchemaCtor()
	e.emitApplyDefaults()
	e.emitDecodeFile()
	e.emitApplyTo(shadowName(m.TypeName), m.Fields, "")
	e.emitApplyEnv()
	switch flagsMode {
	case flagsPFlag:
		e.emitPFlagHooks()
	case flagsStd:
		e.emitStdFlagHooks()
	}
	e.emitFastPaths()
	e.emitPrintConfig()
	if e.needQuoteKey {
		e.decl().Func().Id(e.quoteKeyName()).Params(Id("k").String()).String().Block(
			If(Qual("strings", "ContainsAny").Call(Id("k"), Lit(".["))).Block(
				Return(Lit(`"`).Op("+").Qual("strings", "NewReplacer").Call(Lit(`\`), Lit(`\\`), Lit(`"`), Lit(`\"`)).Dot("Replace").Call(Id("k")).Op("+").Lit(`"`)),
			),
			Return(Id("k")),
		)
	}

	src, err := blankUnusedParams([]byte(fmt.Sprintf("%#v", e.f)))
	if err != nil {
		return nil, err
	}
	return imports.Process("", src, &imports.Options{FormatOnly: true, Comments: true, TabIndent: true, TabWidth: 8})
}

// blankUnusedParams renames each function parameter the body never uses to
// _. The generated functions fill Schema and Hooks fields, so their
// signatures are fixed even when a config type needs only some of the
// parameters.
func blankUnusedParams(src []byte) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			continue
		}
		used := usedNames(fn.Body)
		for _, field := range fn.Type.Params.List {
			for _, name := range field.Names {
				if !used[name.Name] {
					name.Name = "_"
				}
			}
		}
	}
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, f); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// usedNames returns the identifiers n refers to, leaving out the field and
// method names after a dot.
func usedNames(n ast.Node) map[string]bool {
	used := map[string]bool{}
	var visit func(ast.Node) bool
	visit = func(n ast.Node) bool {
		switch n := n.(type) {
		case *ast.SelectorExpr:
			ast.Inspect(n.X, visit)
			return false
		case *ast.Ident:
			used[n.Name] = true
		}
		return true
	}
	ast.Inspect(n, visit)
	return used
}

// decl starts a new top-level declaration, separated from the previous
// one by a blank line, and returns the file to add it to.
func (e *emitter) decl() *File {
	e.f.Line()
	return e.f
}

func shadowName(typeName string) string { return lowerFirst(typeName) + "Shadow" }

func (e *emitter) shadowFor(t types.Type) string {
	named, ok := t.(*types.Named)
	if !ok {
		panic("shadowFor: not a named type")
	}
	return shadowName(named.Obj().Name())
}

// goName returns the shadow field name: the last element of a promoted
// Go path.
func goName(f *Field) string {
	parts := strings.Split(f.GoName, ".")
	return parts[len(parts)-1]
}

// cfgSel renders recv followed by the field's Go path, which may be
// promoted.
func cfgSel(recv string, f *Field) *Statement {
	s := Id(recv)
	for _, p := range strings.Split(f.GoName, ".") {
		s = s.Dot(p)
	}
	return s
}

func (e *emitter) emitSchemaCtor() {
	n := e.m.TypeName
	d := Dict{
		Id("ApplyDefaults"): Id(lowerFirst(n) + "ApplyDefaults"),
		Id("DecodeFile"):    Id(lowerFirst(n) + "DecodeFile"),
		Id("ApplyEnv"):      Id(lowerFirst(n) + "ApplyEnv"),
	}
	if req := requiredPaths(e.m.Fields, ""); len(req) > 0 {
		lits := make([]Code, 0, len(req))
		for _, p := range req {
			lits = append(lits, Lit(p))
		}
		d[Id("Required")] = Index().String().Values(lits...)
	}
	if cond := e.condRequired(e.m.Fields, pathExpr{}, func(f *Field) *Statement { return cfgSel("cfg", f) }, false, 0); len(cond) > 0 {
		fn := lowerFirst(n) + "ConditionalRequired"
		d[Id("ConditionalRequired")] = Id(fn)
		body := append([]Code{Var().Id("req").Index().String()}, cond...)
		body = append(body, Return(Id("req")))
		e.decl().Func().Id(fn).Params(Id("cfg").Op("*").Id(n)).Index().String().Block(body...)
	}
	e.decl().Comment(fmt.Sprintf("%sSchema returns the generated schema for %s.", n, n))
	e.f.Func().Id(n+"Schema").Params().Op("*").Qual(pkgCfg, "Schema").Index(Id(n)).Block(
		Return(Op("&").Qual(pkgCfg, "Schema").Index(Id(n)).Values(d)),
	)
}

// requiredPaths collects dotted paths of required:"true" fields.
func requiredPaths(fields []*Field, prefix string) []string {
	var out []string
	for _, f := range fields {
		p := joinPath(prefix, f.Tag)
		if f.Required {
			out = append(out, p)
		}
		if f.Kind == KindStruct {
			out = append(out, requiredPaths(f.Fields, p)...)
		}
	}
	return out
}

// condRequired returns statements appending to req the paths of
// required:"true" fields that apply only when their container exists: an
// optional struct some layer allocated, or an element of a list or map.
// sel selects a field of fields, and depth numbers the generated variables.
func (e *emitter) condRequired(fields []*Field, p pathExpr, sel func(*Field) *Statement, cond bool, depth int) []Code {
	var out []Code
	for _, f := range fields {
		fp := p.child(f.Tag)
		if p.v == "" && p.suffix == "" {
			fp = pathExpr{suffix: f.Tag}
		}
		if cond && f.Required {
			out = append(out, Id("req").Op("=").Append(Id("req"), fp.code()))
		}
		switch f.Kind {
		case KindStruct:
			out = append(out, e.condRequired(f.Fields, fp, sel, cond, depth)...)
		case KindPointer:
			if f.Elem.Kind != KindStruct {
				continue
			}
			v := depthName("p", depth)
			inner := e.condRequired(f.Elem.Fields, fp, func(sf *Field) *Statement { return relSel(Id(v), sf) }, true, depth+1)
			if len(inner) > 0 {
				out = append(out, If(Id(v).Op(":=").Add(sel(f)), Id(v).Op("!=").Nil()).Block(inner...))
			}
		case KindSliceStruct, KindMapStruct:
			out = append(out, e.condRequiredElems(f, fp, sel(f), depth)...)
		default:
		}
	}
	return out
}

// condRequiredElems is condRequired for every element of the list or map f,
// selected by coll. Map keys are visited in sorted order so the first
// missing path reported is stable.
func (e *emitter) condRequiredElems(f *Field, fp pathExpr, coll *Statement, depth int) []Code {
	el, idx := depthName("el", depth), depthName("rp", depth)
	usesEl := false
	inner := e.condRequired(f.Elem.Fields, pathExpr{v: idx}, func(sf *Field) *Statement {
		usesEl = true
		return relSel(Id(el), sf)
	}, true, depth+1)
	if len(inner) == 0 {
		return nil
	}
	if f.Kind == KindSliceStruct {
		i := depthName("ri", depth)
		vars := Id(i)
		if usesEl {
			vars = List(Id(i), Id(el))
		}
		body := append([]Code{Id(idx).Op(":=").Add(fp.with("[")).Op("+").Qual("strconv", "Itoa").Call(Id(i)).Op("+").Lit("]")}, inner...)
		return []Code{For(vars.Op(":=").Range().Add(coll)).Block(body...)}
	}
	k := depthName("rk", depth)
	body := []Code{Id(idx).Op(":=").Add(fp.with(".")).Op("+").Id(e.quoteKeyName()).Call(Id(k))}
	if usesEl {
		body = append(body, Id(el).Op(":=").Add(coll.Clone()).Index(Id(k)))
	}
	body = append(body, inner...)
	return []Code{For(List(Id("_"), Id(k)).Op(":=").Range().Qual("slices", "Sorted").Call(Qual("maps", "Keys").Call(coll))).Block(body...)}
}
