package main

import (
	"encoding/json/jsontext"
	jsonv2 "encoding/json/v2"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// emitJSONSchema renders a JSON Schema (draft-07 subset) for the config
// type: types, descriptions, defaults, required, additionalProperties
// false (matching the generated decoder's unknown-key rejection).
func emitJSONSchema(m *Model) ([]byte, error) {
	root := schemaObject(m.Fields)
	root["$schema"] = "http://json-schema.org/draft-07/schema#"
	root["title"] = m.TypeName
	b, err := jsonv2.Marshal(root, jsonv2.Deterministic(true), jsontext.WithIndent("  "))
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func schemaObject(fields []*Field) map[string]any {
	props := map[string]any{}
	var required []string
	for _, f := range fields {
		props[f.Tag] = schemaField(f)
		if f.Required {
			required = append(required, f.Tag)
		}
	}
	obj := map[string]any{
		"type":                 "object",
		"properties":           props,
		"additionalProperties": false,
	}
	if len(required) > 0 {
		obj["required"] = required
	}
	return obj
}

func schemaField(f *Field) map[string]any {
	s := map[string]any{}
	if f.Desc != "" {
		s["description"] = f.Desc
	}
	switch f.Kind {
	case KindString, KindDuration, KindStdSlot, KindTextLeaf:
		s["type"] = "string"
	case KindBool:
		s["type"] = "boolean"
	case KindInt, KindUint:
		s["type"] = "integer"
	case KindFloat:
		s["type"] = "number"
	case KindStruct:
		for k, v := range schemaObject(f.Fields) {
			s[k] = v
		}
	case KindPointer:
		inner := *f.Elem
		inner.Desc = ""
		for k, v := range schemaField(&inner) {
			s[k] = v
		}
	case KindSliceScalar, KindSliceStruct:
		s["type"] = "array"
		s["items"] = schemaField(f.Elem)
	case KindMapScalar, KindMapStruct:
		s["type"] = "object"
		s["additionalProperties"] = schemaField(f.Elem)
	}
	if f.Default != "" {
		if d := schemaDefault(f); d != nil {
			s["default"] = d
		}
	}
	return s
}

func schemaDefault(f *Field) any {
	switch f.Kind {
	case KindString, KindDuration, KindStdSlot:
		return f.Default
	case KindBool:
		v, _ := strconv.ParseBool(f.Default)
		return v
	case KindInt:
		v, _ := strconv.ParseInt(f.Default, 10, 64)
		return v
	case KindUint:
		v, _ := strconv.ParseUint(f.Default, 10, 64)
		return v
	case KindFloat:
		v, _ := strconv.ParseFloat(f.Default, 64)
		return v
	case KindSliceScalar:
		parts := strings.Split(f.Default, ",")
		out := make([]any, len(parts))
		for i, p := range parts {
			out[i] = p
		}
		return out
	case KindPointer:
		inner := *f.Elem
		inner.Default = f.Default
		return schemaDefault(&inner)
	}
	return nil
}

// emitSample renders a commented YAML sample: every key at its default,
// descriptions as comments. YAML is chosen because it carries comments;
// the sample documents shape and defaults regardless of which decoder the
// application wires.
func emitSample(m *Model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# Sample configuration for %s.\n# Generated by configulator. DO NOT EDIT.\n", m.TypeName)
	sampleFields(&b, m.Fields, 0)
	return []byte(b.String())
}

func sampleFields(b *strings.Builder, fields []*Field, depth int) {
	ind := strings.Repeat("  ", depth)
	for _, f := range fields {
		if f.Desc != "" {
			fmt.Fprintf(b, "%s# %s\n", ind, f.Desc)
		}
		switch f.Kind {
		case KindStruct:
			fmt.Fprintf(b, "%s%s:\n", ind, f.Tag)
			sampleFields(b, f.Fields, depth+1)
		case KindSliceStruct:
			fmt.Fprintf(b, "%s# %s: []  # list of objects:\n", ind, f.Tag)
			fmt.Fprintf(b, "%s# %s:\n", ind, f.Tag)
			for _, ef := range f.Elem.Fields {
				fmt.Fprintf(b, "%s#   - %s: %s\n", ind, ef.Tag, sampleValue(ef))
				break
			}
		case KindMapStruct, KindMapScalar:
			fmt.Fprintf(b, "%s# %s: {}  # map\n", ind, f.Tag)
		default:
			val := sampleValue(f)
			if f.Secret {
				val = `"(secret)"`
			}
			if f.Default == "" && f.Kind != KindBool {
				fmt.Fprintf(b, "%s# %s: %s\n", ind, f.Tag, val)
			} else {
				fmt.Fprintf(b, "%s%s: %s\n", ind, f.Tag, val)
			}
		}
	}
}

func sampleValue(f *Field) string {
	if f.Default != "" {
		switch f.Kind {
		case KindString, KindDuration, KindStdSlot:
			return strconv.Quote(f.Default)
		case KindSliceScalar:
			return "[" + f.Default + "]"
		default:
			return f.Default
		}
	}
	switch f.Kind {
	case KindString, KindTextLeaf, KindStdSlot:
		return `""`
	case KindBool:
		return "false"
	case KindInt, KindUint:
		return "0"
	case KindFloat:
		return "0.0"
	case KindDuration:
		return strconv.Quote(time.Duration(0).String())
	case KindSliceScalar:
		return "[]"
	case KindPointer:
		return sampleValue(f.Elem)
	}
	return `""`
}
