// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	"github.com/USA-RedDragon/configulator/v2/impl"
)

type configShadow struct {
	Listen  *string        `json:"listen" toml:"listen" yaml:"listen"`
	Timeout *impl.Duration `json:"timeout" toml:"timeout" yaml:"timeout"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.Listen = ":8080"
	set("listen", configulator.LayerDefault, "default tag")
	cfg.Timeout = time.Duration(int64(30000000000))
	set("timeout", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.Listen != nil {
		cfg.Listen = *s.Listen
		set("listen", configulator.LayerFile, file)
	}
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := impl.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "listen"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Listen = v
			set("listen", configulator.LayerEnv, n)
		}
	}
	if n := impl.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "timeout"); true {
		if v, ok := ec.Getenv(n); ok {
			d, err := time.ParseDuration(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "timeout",
					Source: n,
					Value:  v,
				}
			}
			cfg.Timeout = d
			set("timeout", configulator.LayerEnv, n)
		}
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "listen":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Listen = &str
			default:
				return fmt.Errorf("listen: expected a string, got %v", v.Kind())
			}
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return err
				}
				s.Timeout = &slot
			default:
				return fmt.Errorf("timeout: expected a text scalar (e.g. \"30s\"), got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("listen = %v\n", c.Listen))
	b.WriteString(fmt.Sprintf("timeout = %v\n", c.Timeout))
	return b.String()
}
