// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	"strings"
	"time"
)

type configShadow struct {
	Listen  *string                `json:"listen" toml:"listen" yaml:"listen"`
	Timeout *configulator.Duration `json:"timeout" toml:"timeout" yaml:"timeout"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.Listen = ":8080"
	set("listen", configulator.LayerDefault, "default tag")
	cfg.Timeout = time.Duration(int64(30000000000)) // 30s, parsed at generate time from "30s"
	set("timeout", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.Listen != nil {
		cfg.Listen = *s.Listen
		set("listen", configulator.LayerFile, file)
	}
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "listen"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Listen = v
			set("listen", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "timeout"); true {
		if v, ok := ec.Getenv(n); ok {
			d, err := time.ParseDuration(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "timeout",
					Source: n,
					Value:  v,
				}
			}
			cfg.Timeout = d
			set("timeout", configulator.LayerEnv, n)
		}
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "listen":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Listen = &str
			default:
				return fmt.Errorf("listen: expected a string, got %v", v.Kind())
			}
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				var slot configulator.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return err
				}
				s.Timeout = &slot
			default:
				return fmt.Errorf("timeout: expected a text scalar (e.g. \"30s\"), got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("listen = %v\n", c.Listen))
	b.WriteString(fmt.Sprintf("timeout = %v\n", c.Timeout))
	return b.String()
}
