// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
)

type dBConfigShadow struct {
	URL  *string `json:"url"  toml:"url"  yaml:"url"`
	Pool *uint16 `json:"pool" toml:"pool" yaml:"pool"`
}

type configShadow struct {
	DB *dBConfigShadow `json:"db" toml:"db" yaml:"db"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.DB.URL = "postgres://localhost/app"
	set("db.url", configulator.LayerDefault, "default tag")
	cfg.DB.Pool = uint16(10)
	set("db.pool", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.DB != nil {
		if s.DB.URL != nil {
			cfg.DB.URL = *s.DB.URL
			set("db.url", configulator.LayerFile, file)
		}
		if s.DB.Pool != nil {
			cfg.DB.Pool = *s.DB.Pool
			set("db.pool", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("db", "url"); ok {
		cfg.DB.URL = v
		set("db.url", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("db", "pool"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.pool",
				Source: n,
				Value:  v,
			}
		}
		cfg.DB.Pool = uint16(p)
		set("db.pool", configulator.LayerEnv, n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "db":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub dBConfigShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.DB = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return fmt.Errorf("unknown key %q", tok.String())
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

func (s *dBConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return fmt.Errorf("url: expected a string, got %v", v.Kind())
			}
		case "pool":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("pool: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("pool: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Pool = &val
			default:
				return fmt.Errorf("pool: expected a number, got %v", v.Kind())
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return fmt.Errorf("unknown key %q", tok.String())
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*dBConfigShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "db.url = %v\n", c.DB.URL)
	fmt.Fprintf(&b, "db.pool = %v\n", c.DB.Pool)
	return b.String()
}
