// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"flag"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cstd "github.com/USA-RedDragon/configulator/v2/flags/std"
)

type configShadow struct {
	Listen *string `json:"listen" toml:"listen" yaml:"listen"`
	Debug  *bool   `json:"debug"  toml:"debug"  yaml:"debug"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.Listen = ":8080"
	set("listen", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.Listen != nil {
		cfg.Listen = *s.Listen
		set("listen", configulator.LayerFile, file)
	}
	if s.Debug != nil {
		cfg.Debug = *s.Debug
		set("debug", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("listen"); ok {
		cfg.Listen = v
		set("listen", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("debug"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "debug",
				Source: n,
				Value:  v,
			}
		}
		cfg.Debug = p
		set("debug", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigStdFlagHooks returns the stdlib-flag hooks for Config.
func ConfigStdFlagHooks() cstd.Hooks[Config] {
	return cstd.Hooks[Config]{
		Apply:    configApplyStdFlags,
		Register: configRegisterStdFlags,
	}
}

func configRegisterStdFlags(fs *flag.FlagSet, o *cstd.Options) error {
	names := []string{
		"listen",
		"debug",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], ":8080", "listen address")
	fs.Bool(names[1], false, "debug mode")
	return nil
}

func configApplyStdFlags(cfg *Config, fs *flag.FlagSet, o *cstd.Options, isSet map[string]bool, sep string, set configulator.SetOrigin) error {
	if fn := "listen"; isSet[fn] {
		pv := fs.Lookup(fn).Value.(flag.Getter).Get().(string)
		cfg.Listen = pv
		set("listen", configulator.LayerCLI, "-"+fn)
	}
	if fn := "debug"; isSet[fn] {
		pv := fs.Lookup(fn).Value.(flag.Getter).Get().(bool)
		cfg.Debug = pv
		set("debug", configulator.LayerCLI, "-"+fn)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "listen":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Listen = &str
			default:
				return fmt.Errorf("listen: expected a string, got %v", v.Kind())
			}
		case "debug":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Debug = &b
			default:
				return fmt.Errorf("debug: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "listen = %v\n", c.Listen)
	fmt.Fprintf(&b, "debug = %v\n", c.Debug)
	return b.String()
}
