// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"flag"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	std "github.com/USA-RedDragon/configulator/v2/flags/std"
	"strconv"
	"strings"
)

type configShadow struct {
	Listen *string `json:"listen" toml:"listen" yaml:"listen"`
	Debug  *bool   `json:"debug" toml:"debug" yaml:"debug"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.Listen = ":8080"
	set("listen", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.Listen != nil {
		cfg.Listen = *s.Listen
		set("listen", configulator.LayerFile, file)
	}
	if s.Debug != nil {
		cfg.Debug = *s.Debug
		set("debug", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "listen"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Listen = v
			set("listen", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "debug"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "debug",
					Source: n,
					Value:  v,
				}
			}
			cfg.Debug = p
			set("debug", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigStdFlagHooks returns the stdlib-flag hooks for Config.
func ConfigStdFlagHooks() std.Hooks[Config] {
	return std.Hooks[Config]{
		Apply:    configApplyStdFlags,
		Register: configRegisterStdFlags,
	}
}
func configRegisterStdFlags(fs *flag.FlagSet, o *std.Options) error {
	for _, fn := range []string{strings.Join([]string{"listen"}, o.Separator), strings.Join([]string{"debug"}, o.Separator)} {
		if fs.Lookup(fn) != nil {
			return fmt.Errorf("flag -%s already registered on this FlagSet", fn)
		}
	}
	fs.String(strings.Join([]string{"listen"}, o.Separator), ":8080", "listen address")
	fs.Bool(strings.Join([]string{"debug"}, o.Separator), false, "debug mode")
	return nil
}
func configApplyStdFlags(cfg *Config, fs *flag.FlagSet, o *std.Options, isSet map[string]bool, set configulator.SetOrigin) error {
	if fn := strings.Join([]string{"listen"}, o.Separator); isSet[fn] {
		pv := fs.Lookup(fn).Value.(flag.Getter).Get().(string)
		cfg.Listen = pv
		set("listen", configulator.LayerCLI, "-"+fn)
	}
	if fn := strings.Join([]string{"debug"}, o.Separator); isSet[fn] {
		pv := fs.Lookup(fn).Value.(flag.Getter).Get().(bool)
		cfg.Debug = pv
		set("debug", configulator.LayerCLI, "-"+fn)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "listen":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Listen = &str
			default:
				return fmt.Errorf("listen: expected a string, got %v", v.Kind())
			}
		case "debug":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Debug = &b
			default:
				return fmt.Errorf("debug: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("listen = %v\n", c.Listen))
	b.WriteString(fmt.Sprintf("debug = %v\n", c.Debug))
	return b.String()
}
