// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package main

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type hTTPConfigShadow struct {
	Host  *string   `json:"host" toml:"host" yaml:"host"`
	Port  *int      `json:"port" toml:"port" yaml:"port"`
	Stuff *[]string `json:"stuff" toml:"stuff" yaml:"stuff"`
}
type configShadow struct {
	HTTP   *hTTPConfigShadow `json:"http" toml:"http" yaml:"http"`
	Enable *bool             `json:"enable" toml:"enable" yaml:"enable"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.HTTP.Host = "localhost"
	set("http.host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.HTTP != nil {
		if s.HTTP.Host != nil {
			cfg.HTTP.Host = *s.HTTP.Host
			set("http.host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.Stuff != nil {
			cfg.HTTP.Stuff = *s.HTTP.Stuff
			set("http.stuff", configulator.LayerFile, file)
		}
	}
	if s.Enable != nil {
		cfg.Enable = *s.Enable
		set("enable", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Host = v
			set("http.host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = int(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "stuff"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Stuff = configulator.SplitList(v, ec.ArraySeparator)
			set("http.stuff", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "enable"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "enable",
					Source: n,
					Value:  v,
				}
			}
			cfg.Enable = p
			set("enable", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"http", "host"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"http", "stuff"}, o.Separator), strings.Join([]string{"enable"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"http", "host"}, o.Separator), "localhost", "host to listen on")
	fs.Int(strings.Join([]string{"http", "port"}, o.Separator), 8080, "port to listen on")
	fs.StringSlice(strings.Join([]string{"http", "stuff"}, o.Separator), nil, "some stuff")
	fs.Bool(strings.Join([]string{"enable"}, o.Separator), false, "enable the service")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"http", "host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "stuff"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.stuff",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Stuff = v
		set("http.stuff", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"enable"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "enable",
				Source: "--" + n,
			}
		}
		cfg.Enable = v
		set("enable", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPConfigShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "enable":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enable = &b
			default:
				return fmt.Errorf("enable: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *hTTPConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "stuff":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("stuff: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("stuff: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Stuff = &out
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*hTTPConfigShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("http.host = %v\n", c.HTTP.Host))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	b.WriteString(fmt.Sprintf("http.stuff = %v\n", c.HTTP.Stuff))
	b.WriteString(fmt.Sprintf("enable = %v\n", c.Enable))
	return b.String()
}
