// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package examplestd

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"flag"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cstd "github.com/USA-RedDragon/configulator/v2/flags/std"
)

type configShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.Host = "localhost"
	set("host", configulator.LayerDefault, "default tag")
	cfg.Port = uint16(8080)
	set("port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.Host != nil {
		cfg.Host = *s.Host
		set("host", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("host"); ok {
		cfg.Host = v
		set("host", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = uint16(p)
		set("port", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigStdFlagHooks returns the stdlib-flag hooks for Config.
func ConfigStdFlagHooks() cstd.Hooks[Config] {
	return cstd.Hooks[Config]{
		Apply:    configApplyStdFlags,
		Register: configRegisterStdFlags,
	}
}

func configRegisterStdFlags(fs *flag.FlagSet, _ *cstd.Options) error {
	names := []string{
		"host",
		"port",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "localhost", "listen address")
	fs.Uint64(names[1], uint64(0x1f90), "listen port")
	return nil
}

func configApplyStdFlags(cfg *Config, fs *flag.FlagSet, _ *cstd.Options, isSet map[string]bool, _ string, set configulator.SetOrigin) error {
	if fn := "host"; isSet[fn] {
		pv := cstd.Get[string](fs, fn)
		cfg.Host = pv
		set("host", configulator.LayerCLI, "-"+fn)
	}
	if fn := "port"; isSet[fn] {
		raw := cstd.Get[uint64](fs, fn)
		if raw > math.MaxUint16 {
			return &configulator.ParseError{
				Err:    fmt.Errorf("%d overflows uint16", raw),
				Path:   "port",
				Source: "-" + fn,
			}
		}
		pv := uint16(raw)
		cfg.Port = pv
		set("port", configulator.LayerCLI, "-"+fn)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("port: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "host = %v\n", c.Host)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	return b.String()
}
