// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package examplestd

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"flag"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	std "github.com/USA-RedDragon/configulator/v2/flags/std"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"math"
	"slices"
	"strconv"
	"strings"
)

type configShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.Host = "localhost"
	set("host", configulator.LayerDefault, "default tag")
	cfg.Port = uint16(8080)
	set("port", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}
func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.Host != nil {
		cfg.Host = *s.Host
		set("host", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := impl.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Host = v
			set("host", configulator.LayerEnv, n)
		}
	}
	if n := impl.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Port = uint16(p)
			set("port", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigStdFlagHooks returns the stdlib-flag hooks for Config.
func ConfigStdFlagHooks() std.Hooks[Config] {
	return std.Hooks[Config]{
		Apply:    configApplyStdFlags,
		Register: configRegisterStdFlags,
	}
}
func configRegisterStdFlags(fs *flag.FlagSet, o *std.Options) error {
	names := []string{strings.Join([]string{"host"}, o.Separator), strings.Join([]string{"port"}, o.Separator)}
	for i, fn := range names {
		if fs.Lookup(fn) != nil || slices.Contains(names[:i], fn) {
			return &configulator.FlagConflictError{
				Existing: fn,
				Flag:     fn,
			}
		}
	}
	fs.String(names[0], "localhost", "listen address")
	fs.Uint64(names[1], uint64(0x1f90), "listen port")
	return nil
}
func configApplyStdFlags(cfg *Config, fs *flag.FlagSet, o *std.Options, isSet map[string]bool, sep string, set configulator.SetOrigin) error {
	if fn := strings.Join([]string{"host"}, o.Separator); isSet[fn] {
		pv := fs.Lookup(fn).Value.(flag.Getter).Get().(string)
		cfg.Host = pv
		set("host", configulator.LayerCLI, "-"+fn)
	}
	if fn := strings.Join([]string{"port"}, o.Separator); isSet[fn] {
		raw := fs.Lookup(fn).Value.(flag.Getter).Get().(uint64)
		if raw > math.MaxUint16 {
			return &configulator.ParseError{
				Err:    fmt.Errorf("%d overflows uint16", raw),
				Path:   "port",
				Source: "-" + fn,
			}
		}
		pv := uint16(raw)
		cfg.Port = pv
		set("port", configulator.LayerCLI, "-"+fn)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("host = %v\n", c.Host))
	b.WriteString(fmt.Sprintf("port = %v\n", c.Port))
	return b.String()
}
