// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package exampleconfig

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type hTTPShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}

type dBShadow struct {
	URL *string `json:"url" toml:"url" yaml:"url"`
}

type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	Timeout  *impl.Duration `json:"timeout"   toml:"timeout"   yaml:"timeout"`
	HTTP     *hTTPShadow    `json:"http"      toml:"http"      yaml:"http"`
	DB       *dBShadow      `json:"db"        toml:"db"        yaml:"db"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
		Required:      []string{"db.url"},
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = "info"
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Timeout = time.Duration(int64(30000000000))
	set("timeout", configulator.LayerDefault, "default tag")
	cfg.HTTP.Host = "localhost"
	set("http.host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return configulator.NewDecodeError(file, err)
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = *s.LogLevel
		set("log-level", configulator.LayerFile, file)
	}
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Host != nil {
			cfg.HTTP.Host = *s.HTTP.Host
			set("http.host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.DB != nil {
		if s.DB.URL != nil {
			cfg.DB.URL = *s.DB.URL
			set("db.url", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("log-level"); ok {
		cfg.LogLevel = v
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: n,
				Value:  v,
			}
		}
		cfg.Timeout = d
		set("timeout", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "host"); ok {
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("db", "url"); ok {
		cfg.DB.URL = v
		set("db.url", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"timeout",
		"http" + o.Separator + "host",
		"http" + o.Separator + "port",
		"db" + o.Separator + "url",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log level")
	fs.Duration(names[1], time.Duration(int64(30000000000)), "request timeout")
	fs.String(names[2], "localhost", "listen address")
	fs.Uint16(names[3], 8080, "listen port")
	fs.String(names[4], "", "database URL")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = v
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "timeout"; fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: "--" + n,
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "db" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.url",
				Source: "--" + n,
			}
		}
		cfg.DB.URL = v
		set("db.url", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError("timeout", v, err)
				}
				s.Timeout = &slot
			default:
				return configJSONError("timeout", v, fmt.Errorf("expected a text scalar (e.g. \"30s\"), got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "db":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("db", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub dBShadow
				if err := sub.decodeJSON(dec, "db"); err != nil {
					return err
				}
				s.DB = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *dBShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "url":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.URL = &str
				default:
					return configJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".url",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "timeout = %v\n", c.Timeout)
	fmt.Fprintf(&b, "http.host = %v\n", c.HTTP.Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	b.WriteString("db.url = (redacted)\n")
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
