// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package exampleconfig

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type hTTPShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}

type dBShadow struct {
	URL *string `json:"url" toml:"url" yaml:"url"`
}

type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	Timeout  *impl.Duration `json:"timeout" toml:"timeout" yaml:"timeout"`
	HTTP     *hTTPShadow    `json:"http" toml:"http" yaml:"http"`
	DB       *dBShadow      `json:"db" toml:"db" yaml:"db"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
		Required:      []string{"db.url"},
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = "info"
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Timeout = time.Duration(int64(30000000000))
	set("timeout", configulator.LayerDefault, "default tag")
	cfg.HTTP.Host = "localhost"
	set("http.host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = *s.LogLevel
		set("log-level", configulator.LayerFile, file)
	}
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Host != nil {
			cfg.HTTP.Host = *s.HTTP.Host
			set("http.host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.DB != nil {
		if s.DB.URL != nil {
			cfg.DB.URL = *s.DB.URL
			set("db.url", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("log-level"); ok {
		cfg.LogLevel = v
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: n,
				Value:  v,
			}
		}
		cfg.Timeout = d
		set("timeout", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "host"); ok {
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("db", "url"); ok {
		cfg.DB.URL = v
		set("db.url", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"timeout"}, o.Separator), strings.Join([]string{"http", "host"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"db", "url"}, o.Separator)}
	for i, name := range names {
		if fs.Lookup(name) != nil || slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log level")
	fs.Duration(names[1], time.Duration(int64(30000000000)), "request timeout")
	fs.String(names[2], "localhost", "listen address")
	fs.Uint16(names[3], uint16(8080), "listen port")
	fs.String(names[4], "", "database URL")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = v
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"timeout"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: "--" + n,
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"db", "url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.url",
				Source: "--" + n,
			}
		}
		cfg.DB.URL = v
		set("db.url", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return err
				}
				s.Timeout = &slot
			default:
				return fmt.Errorf("timeout: expected a text scalar (e.g. \"30s\"), got %v", v.Kind())
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "db":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub dBShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.DB = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

func (s *hTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("port: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*hTTPShadow)(nil)

func (s *dBShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "url":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case 'n':
				case '"':
					str := v.String()
					s.URL = &str
				default:
					return fmt.Errorf("url: expected a string, got %v", v.Kind())
				}
				return nil
			}(); err != nil {
				return errors.New("url: invalid value (redacted)")
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*dBShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "timeout = %v\n", c.Timeout)
	fmt.Fprintf(&b, "http.host = %v\n", c.HTTP.Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	b.WriteString("db.url = (redacted)\n")
	return b.String()
}
