// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type attributesShadow struct {
	Token   *int64  `json:"token"   toml:"token"   yaml:"token"`
	Renamed *string `json:"renamed" toml:"renamed" yaml:"renamed"`
	NoEnv   *string `json:"no-env"  toml:"no-env"  yaml:"no-env"`
	NoFlag  *string `json:"no-flag" toml:"no-flag" yaml:"no-flag"`
	Port    *uint16 `json:"port"    toml:"port"    yaml:"port"`
}

// AttributesSchema returns the generated schema for Attributes.
func AttributesSchema() *configulator.Schema[Attributes] {
	return &configulator.Schema[Attributes]{
		ApplyDefaults: attributesApplyDefaults,
		ApplyEnv:      attributesApplyEnv,
		DecodeFile:    attributesDecodeFile,
	}
}

func attributesApplyDefaults(cfg *Attributes, sep string, set configulator.SetOrigin) error {
	return nil
}

func attributesDecodeFile(data []byte, u configulator.Unmarshal, cfg *Attributes, sep string, set configulator.SetOrigin, file string) error {
	var sh attributesShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *attributesShadow) applyTo(cfg *Attributes, sep string, set configulator.SetOrigin, file string) error {
	if s.Token != nil {
		cfg.Token = *s.Token
		set("token", configulator.LayerFile, file)
	}
	if s.Renamed != nil {
		cfg.Renamed = *s.Renamed
		set("renamed", configulator.LayerFile, file)
	}
	if s.NoEnv != nil {
		cfg.NoEnv = *s.NoEnv
		set("no-env", configulator.LayerFile, file)
	}
	if s.NoFlag != nil {
		cfg.NoFlag = *s.NoFlag
		set("no-flag", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	return nil
}

func attributesApplyEnv(cfg *Attributes, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("token"); ok {
		p, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    impl.Redact(err, v),
				Path:   "token",
				Source: n,
				Value:  "(redacted)",
			}
		}
		cfg.Token = p
		set("token", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("RN"); ok {
		cfg.Renamed = v
		set("renamed", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("no-flag"); ok {
		cfg.NoFlag = v
		set("no-flag", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = uint16(p)
		set("port", configulator.LayerEnv, n)
	}
	return nil
}

// AttributesPFlagHooks returns the pflag hooks for Attributes.
func AttributesPFlagHooks() cpflag.Hooks[Attributes] {
	return cpflag.Hooks[Attributes]{
		Apply:    attributesApplyPFlags,
		Register: attributesRegisterPFlags,
	}
}

func attributesRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"token",
		"rn",
		"no-env",
		"port",
	}
	shorts := []string{"", "", "", "p"}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
		if s := shorts[i]; s != "" {
			if f := fs.ShorthandLookup(s); f != nil {
				return &configulator.FlagConflictError{
					Existing:  f.Name,
					Flag:      name,
					Shorthand: s,
				}
			}
		}
	}
	fs.String(names[0], "", "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.Uint16P(names[3], "p", uint16(0), "")
	return nil
}

func attributesApplyPFlags(cfg *Attributes, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := "token"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "token",
				Source: "--" + n,
			}
		}
		p, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    impl.Redact(err, v),
				Path:   "token",
				Source: "--" + n,
				Value:  "(redacted)",
			}
		}
		cfg.Token = p
		set("token", configulator.LayerCLI, "--"+n)
	}
	if n := "rn"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "renamed",
				Source: "--" + n,
			}
		}
		cfg.Renamed = v
		set("renamed", configulator.LayerCLI, "--"+n)
	}
	if n := "no-env"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "no-env",
				Source: "--" + n,
			}
		}
		cfg.NoEnv = v
		set("no-env", configulator.LayerCLI, "--"+n)
	}
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *attributesShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "token":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindNumber:
					num, err := v.Int()
					if err != nil {
						return fmt.Errorf("token: %w", err)
					}
					val := num
					s.Token = &val
				default:
					return fmt.Errorf("token: expected a number, got %v", v.Kind())
				}
				return nil
			}(); err != nil {
				return errors.New("token: invalid value (redacted)")
			}
		case "renamed":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Renamed = &str
			default:
				return fmt.Errorf("renamed: expected a string, got %v", v.Kind())
			}
		case "no-env":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.NoEnv = &str
			default:
				return fmt.Errorf("no-env: expected a string, got %v", v.Kind())
			}
		case "no-flag":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.NoFlag = &str
			default:
				return fmt.Errorf("no-flag: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("port: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*attributesShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Attributes) PrintConfig() string {
	var b strings.Builder
	b.WriteString("token = (redacted)\n")
	fmt.Fprintf(&b, "renamed = %v\n", c.Renamed)
	fmt.Fprintf(&b, "no-env = %v\n", c.NoEnv)
	fmt.Fprintf(&b, "no-flag = %v\n", c.NoFlag)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	return b.String()
}
