// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"strconv"
	"strings"
)

type serverShadow struct {
	Addr   *string `json:"addr" toml:"addr" yaml:"addr"`
	Weight *uint16 `json:"weight" toml:"weight" yaml:"weight"`
}
type poolShadow struct {
	Size *uint16 `json:"size" toml:"size" yaml:"size"`
}
type collectionsShadow struct {
	Tags     *[]string              `json:"tags" toml:"tags" yaml:"tags"`
	Labels   *map[string]string     `json:"labels" toml:"labels" yaml:"labels"`
	Servers  *[]serverShadow        `json:"servers" toml:"servers" yaml:"servers"`
	Pools    *map[string]poolShadow `json:"pools" toml:"pools" yaml:"pools"`
	LogLevel *string                `json:"log-level" toml:"log-level" yaml:"log-level"`
}

// CollectionsSchema returns the generated schema for Collections.
func CollectionsSchema() *configulator.Schema[Collections] {
	return &configulator.Schema[Collections]{
		ApplyDefaults: collectionsApplyDefaults,
		ApplyEnv:      collectionsApplyEnv,
		DecodeFile:    collectionsDecodeFile,
	}
}
func collectionsApplyDefaults(cfg *Collections, set configulator.SetOrigin) error {
	cfg.Tags = []string{"a", "b"}
	set("tags", configulator.LayerDefault, "default tag")
	cfg.LogLevel = "info"
	set("log-level", configulator.LayerDefault, "default tag")
	return nil
}
func collectionsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Collections, set configulator.SetOrigin, file string) error {
	var sh collectionsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *collectionsShadow) applyTo(cfg *Collections, set configulator.SetOrigin, file string) error {
	if s.Tags != nil {
		cfg.Tags = *s.Tags
		set("tags", configulator.LayerFile, file)
	}
	if s.Labels != nil {
		cfg.Labels = *s.Labels
		set("labels", configulator.LayerFile, file)
	}
	if s.Servers != nil {
		out := make([]Server, len(*s.Servers))
		for i, esh := range *s.Servers {
			var e Server
			idx := "servers[" + strconv.Itoa(i) + "]"
			e.Weight = uint16(1)
			set(idx+".weight", configulator.LayerDefault, "element default")
			if esh.Addr != nil {
				e.Addr = *esh.Addr
				set(idx+".addr", configulator.LayerFile, file)
			}
			if esh.Weight != nil {
				e.Weight = *esh.Weight
				set(idx+".weight", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.Servers = out
		set("servers", configulator.LayerFile, file)
	}
	if s.Pools != nil {
		out := make(map[string]Pool, len(*s.Pools))
		for k, esh := range *s.Pools {
			var e Pool
			key := "pools." + collectionsQuoteKey(k)
			e.Size = uint16(5)
			set(key+".size", configulator.LayerDefault, "element default")
			if esh.Size != nil {
				e.Size = *esh.Size
				set(key+".size", configulator.LayerFile, file)
			}
			out[k] = e
		}
		cfg.Pools = out
		set("pools", configulator.LayerFile, file)
	}
	if s.LogLevel != nil {
		cfg.LogLevel = *s.LogLevel
		set("log-level", configulator.LayerFile, file)
	}
	return nil
}
func collectionsApplyEnv(cfg *Collections, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "tags"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Tags = configulator.SplitList(v, ec.ArraySeparator)
			set("tags", configulator.LayerEnv, n)
		}
	}
	// labels: map — skipped for env (SPEC rule 6, generator warning)
	// servers: []struct — skipped for env (SPEC rule 6, generator warning)
	// pools: map — skipped for env (SPEC rule 6, generator warning)
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = v
			set("log-level", configulator.LayerEnv, n)
		}
	}
	return nil
}

// CollectionsPFlagHooks returns the pflag hooks for Collections.
func CollectionsPFlagHooks() cpflag.Hooks[Collections] {
	return cpflag.Hooks[Collections]{
		Apply:    collectionsApplyPFlags,
		Register: collectionsRegisterPFlags,
	}
}
func collectionsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"tags"}, o.Separator), strings.Join([]string{"log-level"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.StringSlice(strings.Join([]string{"tags"}, o.Separator), []string{"a", "b"}, "")
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "")
	return nil
}
func collectionsApplyPFlags(cfg *Collections, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"tags"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tags",
				Source: "--" + n,
			}
		}
		cfg.Tags = v
		set("tags", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = v
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *collectionsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "tags":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("tags: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("tags: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Tags = &out
			}
		case "labels":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '{' {
					return fmt.Errorf("labels: expected an object, got %v", tok.Kind())
				}
				out := map[string]string{}
				for dec.PeekKind() != '}' {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					mk := kt.String()
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("labels: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out[mk] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Labels = &out
			}
		case "servers":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("servers: expected an array, got %v", tok.Kind())
				}
				out := []serverShadow{}
				for dec.PeekKind() != ']' {
					var el serverShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Servers = &out
			}
		case "pools":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '{' {
					return fmt.Errorf("pools: expected an object, got %v", tok.Kind())
				}
				out := map[string]poolShadow{}
				for dec.PeekKind() != '}' {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					mk := kt.String()
					var el poolShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out[mk] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Pools = &out
			}
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*collectionsShadow)(nil)

func (s *serverShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "addr":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Addr = &str
			default:
				return fmt.Errorf("addr: expected a string, got %v", v.Kind())
			}
		case "weight":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("weight: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Weight = &val
			default:
				return fmt.Errorf("weight: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*serverShadow)(nil)

func (s *poolShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("size: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Size = &val
			default:
				return fmt.Errorf("size: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*poolShadow)(nil)

// collectionsQuoteKey quotes a map key whose characters would make
// a dotted origin path ambiguous.
func collectionsQuoteKey(k string) string {
	for _, c := range k {
		if c == '.' || c == '[' {
			return "\"" + k + "\""
		}
	}
	return k
}
