// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type serverShadow struct {
	Addr   *string `json:"addr"   toml:"addr"   yaml:"addr"`
	Weight *uint16 `json:"weight" toml:"weight" yaml:"weight"`
}

type poolShadow struct {
	Size *uint16 `json:"size" toml:"size" yaml:"size"`
}

type collectionsShadow struct {
	Tags     *[]string              `json:"tags"      toml:"tags"      yaml:"tags"`
	Labels   *map[string]string     `json:"labels"    toml:"labels"    yaml:"labels"`
	Servers  *[]serverShadow        `json:"servers"   toml:"servers"   yaml:"servers"`
	Pools    *map[string]poolShadow `json:"pools"     toml:"pools"     yaml:"pools"`
	LogLevel *string                `json:"log-level" toml:"log-level" yaml:"log-level"`
}

// CollectionsSchema returns the generated schema for Collections.
func CollectionsSchema() *configulator.Schema[Collections] {
	return &configulator.Schema[Collections]{
		ApplyDefaults: collectionsApplyDefaults,
		ApplyEnv:      collectionsApplyEnv,
		DecodeFile:    collectionsDecodeFile,
	}
}

func collectionsApplyDefaults(cfg *Collections, sep string, set configulator.SetOrigin) error {
	{
		lst := impl.SplitList("a,b", sep)
		cfg.Tags = lst
		set("tags", configulator.LayerDefault, "default tag")
	}
	cfg.LogLevel = "info"
	set("log-level", configulator.LayerDefault, "default tag")
	return nil
}

func collectionsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Collections, sep string, set configulator.SetOrigin, file string) error {
	var sh collectionsShadow
	if err := u(data, &sh); err != nil {
		return configulator.NewDecodeError(file, err)
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *collectionsShadow) applyTo(cfg *Collections, _ string, set configulator.SetOrigin, file string) error {
	if s.Tags != nil {
		cfg.Tags = *s.Tags
		set("tags", configulator.LayerFile, file)
	}
	if s.Labels != nil {
		cfg.Labels = *s.Labels
		set("labels", configulator.LayerFile, file)
	}
	if s.Servers != nil {
		out := make([]Server, len(*s.Servers))
		for i, esh := range *s.Servers {
			var e Server
			idx := "servers[" + strconv.Itoa(i) + "]"
			e.Weight = uint16(1)
			set(idx+".weight", configulator.LayerDefault, "element default")
			if esh.Addr != nil {
				e.Addr = *esh.Addr
				set(idx+".addr", configulator.LayerFile, file)
			}
			if esh.Weight != nil {
				e.Weight = *esh.Weight
				set(idx+".weight", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.Servers = out
		set("servers", configulator.LayerFile, file)
	}
	if s.Pools != nil {
		out := make(map[string]Pool, len(*s.Pools))
		for k, esh := range *s.Pools {
			var e Pool
			key := "pools." + collectionsQuoteKey(k)
			e.Size = uint16(5)
			set(key+".size", configulator.LayerDefault, "element default")
			if esh.Size != nil {
				e.Size = *esh.Size
				set(key+".size", configulator.LayerFile, file)
			}
			out[k] = e
		}
		cfg.Pools = out
		set("pools", configulator.LayerFile, file)
	}
	if s.LogLevel != nil {
		cfg.LogLevel = *s.LogLevel
		set("log-level", configulator.LayerFile, file)
	}
	return nil
}

func collectionsApplyEnv(cfg *Collections, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("tags"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.Tags = lst
		set("tags", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("log-level"); ok {
		cfg.LogLevel = v
		set("log-level", configulator.LayerEnv, n)
	}
	return nil
}

// CollectionsPFlagHooks returns the pflag hooks for Collections.
func CollectionsPFlagHooks() cpflag.Hooks[Collections] {
	return cpflag.Hooks[Collections]{
		Apply:    collectionsApplyPFlags,
		Register: collectionsRegisterPFlags,
	}
}

func collectionsRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"tags",
		"log-level",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.StringSlice(names[0], nil, "")
	fs.Lookup(names[0]).DefValue = "[a,b]"
	fs.String(names[1], "info", "")
	return nil
}

func collectionsApplyPFlags(cfg *Collections, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "tags"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tags",
				Source: "--" + n,
			}
		}
		cfg.Tags = v
		set("tags", configulator.LayerCLI, "--"+n)
	}
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = v
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *collectionsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "tags":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return collectionsJSONError("tags", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return collectionsJSONError("tags"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Tags = &out
			}
		case "labels":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return collectionsJSONError("labels", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				out := map[string]string{}
				for dec.PeekKind() != jsontext.KindEndObject {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					key := kt.String()
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return collectionsJSONError("labels"+"."+collectionsQuoteKey(key), v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out[key] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Labels = &out
			}
		case "servers":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return collectionsJSONError("servers", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []serverShadow{}
				for dec.PeekKind() != jsontext.KindEndArray {
					ep := "servers" + "[" + strconv.Itoa(len(out)) + "]"
					et, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if et.Kind() != jsontext.KindBeginObject {
						return collectionsJSONError(ep, et, fmt.Errorf("expected an object, got %v", et.Kind()))
					}
					var el serverShadow
					if err := el.decodeJSON(dec, ep); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Servers = &out
			}
		case "pools":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return collectionsJSONError("pools", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				out := map[string]poolShadow{}
				for dec.PeekKind() != jsontext.KindEndObject {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					key := kt.String()
					ep := "pools" + "." + collectionsQuoteKey(key)
					et, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if et.Kind() != jsontext.KindBeginObject {
						return collectionsJSONError(ep, et, fmt.Errorf("expected an object, got %v", et.Kind()))
					}
					var el poolShadow
					if err := el.decodeJSON(dec, ep); err != nil {
						return err
					}
					out[key] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Pools = &out
			}
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return collectionsJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: collectionsQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*collectionsShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *serverShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "addr":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Addr = &str
			default:
				return collectionsJSONError(path+".addr", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "weight":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return collectionsJSONError(path+".weight", v, err)
				}
				if raw > math.MaxUint16 {
					return collectionsJSONError(path+".weight", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Weight = &num
			default:
				return collectionsJSONError(path+".weight", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + collectionsQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *poolShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return collectionsJSONError(path+".size", v, err)
				}
				if raw > math.MaxUint16 {
					return collectionsJSONError(path+".size", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Size = &num
			default:
				return collectionsJSONError(path+".size", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + collectionsQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// collectionsJSONError returns a ParseError for the JSON token v at path.
func collectionsJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Collections) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "tags = %v\n", c.Tags)
	fmt.Fprintf(&b, "labels = %v\n", c.Labels)
	fmt.Fprintf(&b, "servers = %v\n", c.Servers)
	fmt.Fprintf(&b, "pools = %v\n", c.Pools)
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	return b.String()
}

func collectionsQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
