// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type complexShadow struct {
	Z        *impl.Complex128   `json:"z"        toml:"z"        yaml:"z"`
	Exponent *impl.Complex128   `json:"exponent" toml:"exponent" yaml:"exponent"`
	W        *impl.Complex64    `json:"w"        toml:"w"        yaml:"w"`
	Zs       *[]impl.Complex128 `json:"zs"       toml:"zs"       yaml:"zs"`
}

// ComplexSchema returns the generated schema for Complex.
func ComplexSchema() *configulator.Schema[Complex] {
	return &configulator.Schema[Complex]{
		ApplyDefaults: complexApplyDefaults,
		ApplyEnv:      complexApplyEnv,
		DecodeFile:    complexDecodeFile,
	}
}

func complexApplyDefaults(cfg *Complex, _ string, set configulator.SetOrigin) error {
	{
		var slot impl.Complex128
		_ = slot.UnmarshalText([]byte("1+2i"))
		v, _ := slot.Value()
		cfg.Z = v
		set("z", configulator.LayerDefault, "default tag")
	}
	return nil
}

func complexDecodeFile(data []byte, u configulator.Unmarshal, cfg *Complex, sep string, set configulator.SetOrigin, file string) error {
	var sh complexShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *complexShadow) applyTo(cfg *Complex, _ string, set configulator.SetOrigin, file string) error {
	if s.Z != nil {
		v, ok := s.Z.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "z",
			}
		}
		cfg.Z = v
		set("z", configulator.LayerFile, file)
	}
	if s.Exponent != nil {
		v, ok := s.Exponent.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "exponent",
			}
		}
		cfg.Exponent = v
		set("exponent", configulator.LayerFile, file)
	}
	if s.W != nil {
		v, ok := s.W.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "w",
			}
		}
		cfg.W = v
		set("w", configulator.LayerFile, file)
	}
	if s.Zs != nil {
		{
			lst := make([]complex128, len(*s.Zs))
			for li, lx := range *s.Zs {
				lv, ok := lx.Value()
				if !ok {
					return &configulator.OpaqueSpellingError{
						Hint: "\"1+2i\"",
						Path: "zs",
					}
				}
				lst[li] = lv
			}
			cfg.Zs = lst
		}
		set("zs", configulator.LayerFile, file)
	}
	return nil
}

func complexApplyEnv(cfg *Complex, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "z"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Z = sv
		set("z", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "exponent"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Exponent = sv
		set("exponent", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "w"); ok {
		var slot impl.Complex64
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "w",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.W = sv
		set("w", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "zs"); ok {
		lp := impl.SplitList(v, ec.ArraySeparator)
		lst := make([]complex128, len(lp))
		for li, ls := range lp {
			var slot impl.Complex128
			if err := slot.UnmarshalText([]byte(ls)); err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "zs",
					Source: n,
					Value:  v,
				}
			}
			sv, _ := slot.Value()
			lx := sv
			lst[li] = lx
		}
		cfg.Zs = lst
		set("zs", configulator.LayerEnv, n)
	}
	return nil
}

// ComplexPFlagHooks returns the pflag hooks for Complex.
func ComplexPFlagHooks() cpflag.Hooks[Complex] {
	return cpflag.Hooks[Complex]{
		Apply:    complexApplyPFlags,
		Register: complexRegisterPFlags,
	}
}

func complexRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"z",
		"exponent",
		"w",
		"zs",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "1+2i", "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.StringSlice(names[3], nil, "")
	return nil
}

func complexApplyPFlags(cfg *Complex, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "z"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Z = sv
		set("z", configulator.LayerCLI, "--"+n)
	}
	if n := "exponent"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Exponent = sv
		set("exponent", configulator.LayerCLI, "--"+n)
	}
	if n := "w"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "w",
				Source: "--" + n,
			}
		}
		var slot impl.Complex64
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "w",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.W = sv
		set("w", configulator.LayerCLI, "--"+n)
	}
	if n := "zs"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "zs",
				Source: "--" + n,
			}
		}
		lp := v
		lst := make([]complex128, len(lp))
		for li, ls := range lp {
			var slot impl.Complex128
			if err := slot.UnmarshalText([]byte(ls)); err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "zs",
					Source: "--" + n,
					Value:  strings.Join(v, ","),
				}
			}
			sv, _ := slot.Value()
			lx := sv
			lst[li] = lx
		}
		cfg.Zs = lst
		set("zs", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *complexShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "z":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return complexJSONError("z", v, err)
				}
				s.Z = &slot
			default:
				return complexJSONError("z", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "exponent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return complexJSONError("exponent", v, err)
				}
				s.Exponent = &slot
			default:
				return complexJSONError("exponent", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "w":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex64
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return complexJSONError("w", v, err)
				}
				s.W = &slot
			default:
				return complexJSONError("w", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "zs":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return complexJSONError("zs", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []impl.Complex128{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString && v.Kind() != jsontext.KindNumber {
						return complexJSONError("zs"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
					}
					var el impl.Complex128
					if err := el.UnmarshalText([]byte(v.String())); err != nil {
						return complexJSONError("zs"+"["+strconv.Itoa(len(out))+"]", v, err)
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Zs = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: complexQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*complexShadow)(nil)

// complexJSONError returns a ParseError for the JSON token v at path.
func complexJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Complex) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "z = %v\n", c.Z)
	fmt.Fprintf(&b, "exponent = %v\n", c.Exponent)
	fmt.Fprintf(&b, "w = %v\n", c.W)
	fmt.Fprintf(&b, "zs = %v\n", c.Zs)
	return b.String()
}

func complexQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
