// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strings"
	"time"
)

type durationsShadow struct {
	Timeout *configulator.Duration `json:"timeout" toml:"timeout" yaml:"timeout"`
	Label   *string                `json:"label" toml:"label" yaml:"label"`
}

// DurationsSchema returns the generated schema for Durations.
func DurationsSchema() *configulator.Schema[Durations] {
	return &configulator.Schema[Durations]{
		ApplyDefaults: durationsApplyDefaults,
		ApplyEnv:      durationsApplyEnv,
		DecodeFile:    durationsDecodeFile,
	}
}
func durationsApplyDefaults(cfg *Durations, set configulator.SetOrigin) error {
	cfg.Timeout = time.Duration(int64(30000000000)) // 30s, parsed at generate time from "30s"
	set("timeout", configulator.LayerDefault, "default tag")
	return nil
}
func durationsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Durations, set configulator.SetOrigin, file string) error {
	var sh durationsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *durationsShadow) applyTo(cfg *Durations, set configulator.SetOrigin, file string) error {
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	if s.Label != nil {
		cfg.Label = *s.Label
		set("label", configulator.LayerFile, file)
	}
	return nil
}
func durationsApplyEnv(cfg *Durations, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "timeout"); true {
		if v, ok := ec.Getenv(n); ok {
			d, err := time.ParseDuration(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "timeout",
					Source: n,
					Value:  v,
				}
			}
			cfg.Timeout = d
			set("timeout", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "label"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Label = v
			set("label", configulator.LayerEnv, n)
		}
	}
	return nil
}

// DurationsPFlagHooks returns the pflag hooks for Durations.
func DurationsPFlagHooks() cpflag.Hooks[Durations] {
	return cpflag.Hooks[Durations]{
		Apply:    durationsApplyPFlags,
		Register: durationsRegisterPFlags,
	}
}
func durationsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"timeout"}, o.Separator), strings.Join([]string{"label"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.Duration(strings.Join([]string{"timeout"}, o.Separator), time.Duration(int64(30000000000)), "")
	fs.String(strings.Join([]string{"label"}, o.Separator), "", "")
	return nil
}
func durationsApplyPFlags(cfg *Durations, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"timeout"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: "--" + n,
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"label"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "label",
				Source: "--" + n,
			}
		}
		cfg.Label = v
		set("label", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *durationsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				var slot configulator.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return err
				}
				s.Timeout = &slot
			default:
				return fmt.Errorf("timeout: expected a text scalar (e.g. \"30s\"), got %v", v.Kind())
			}
		case "label":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Label = &str
			default:
				return fmt.Errorf("label: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*durationsShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Durations) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("timeout = %v\n", c.Timeout))
	b.WriteString(fmt.Sprintf("label = %v\n", c.Label))
	return b.String()
}
