// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type durationsShadow struct {
	Timeout *impl.Duration `json:"timeout" toml:"timeout" yaml:"timeout"`
	Label   *string        `json:"label"   toml:"label"   yaml:"label"`
}

// DurationsSchema returns the generated schema for Durations.
func DurationsSchema() *configulator.Schema[Durations] {
	return &configulator.Schema[Durations]{
		ApplyDefaults: durationsApplyDefaults,
		ApplyEnv:      durationsApplyEnv,
		DecodeFile:    durationsDecodeFile,
	}
}

func durationsApplyDefaults(cfg *Durations, _ string, set configulator.SetOrigin) error {
	cfg.Timeout = time.Duration(int64(30000000000))
	set("timeout", configulator.LayerDefault, "default tag")
	return nil
}

func durationsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Durations, sep string, set configulator.SetOrigin, file string) error {
	var sh durationsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *durationsShadow) applyTo(cfg *Durations, _ string, set configulator.SetOrigin, file string) error {
	if s.Timeout != nil {
		v, ok := s.Timeout.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"30s\"",
				Path: "timeout",
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerFile, file)
	}
	if s.Label != nil {
		cfg.Label = *s.Label
		set("label", configulator.LayerFile, file)
	}
	return nil
}

func durationsApplyEnv(cfg *Durations, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: n,
				Value:  v,
			}
		}
		cfg.Timeout = d
		set("timeout", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("label"); ok {
		cfg.Label = v
		set("label", configulator.LayerEnv, n)
	}
	return nil
}

// DurationsPFlagHooks returns the pflag hooks for Durations.
func DurationsPFlagHooks() cpflag.Hooks[Durations] {
	return cpflag.Hooks[Durations]{
		Apply:    durationsApplyPFlags,
		Register: durationsRegisterPFlags,
	}
}

func durationsRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"timeout",
		"label",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.Duration(names[0], time.Duration(int64(30000000000)), "")
	fs.String(names[1], "", "")
	return nil
}

func durationsApplyPFlags(cfg *Durations, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "timeout"; fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeout",
				Source: "--" + n,
			}
		}
		cfg.Timeout = v
		set("timeout", configulator.LayerCLI, "--"+n)
	}
	if n := "label"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "label",
				Source: "--" + n,
			}
		}
		cfg.Label = v
		set("label", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *durationsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "timeout":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return err
				}
				s.Timeout = &slot
			default:
				return fmt.Errorf("timeout: expected a text scalar (e.g. \"30s\"), got %v", v.Kind())
			}
		case "label":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Label = &str
			default:
				return fmt.Errorf("label: expected a string, got %v", v.Kind())
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return fmt.Errorf("unknown key %q", tok.String())
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*durationsShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Durations) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "timeout = %v\n", c.Timeout)
	fmt.Fprintf(&b, "label = %v\n", c.Label)
	return b.String()
}
