// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
)

type embeddedShadow struct {
	Region *string `json:"region" toml:"region" yaml:"region"`
	Zone   *string `json:"zone" toml:"zone" yaml:"zone"`
}

// EmbeddedSchema returns the generated schema for Embedded.
func EmbeddedSchema() *configulator.Schema[Embedded] {
	return &configulator.Schema[Embedded]{
		ApplyDefaults: embeddedApplyDefaults,
		ApplyEnv:      embeddedApplyEnv,
		DecodeFile:    embeddedDecodeFile,
	}
}

func embeddedApplyDefaults(cfg *Embedded, sep string, set configulator.SetOrigin) error {
	cfg.Base.Region = "us-east-1"
	set("region", configulator.LayerDefault, "default tag")
	cfg.Zone = "a"
	set("zone", configulator.LayerDefault, "default tag")
	return nil
}

func embeddedDecodeFile(data []byte, u configulator.Unmarshal, cfg *Embedded, sep string, set configulator.SetOrigin, file string) error {
	var sh embeddedShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *embeddedShadow) applyTo(cfg *Embedded, sep string, set configulator.SetOrigin, file string) error {
	if s.Region != nil {
		cfg.Base.Region = *s.Region
		set("region", configulator.LayerFile, file)
	}
	if s.Zone != nil {
		cfg.Zone = *s.Zone
		set("zone", configulator.LayerFile, file)
	}
	return nil
}

func embeddedApplyEnv(cfg *Embedded, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("region"); ok {
		cfg.Base.Region = v
		set("region", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("zone"); ok {
		cfg.Zone = v
		set("zone", configulator.LayerEnv, n)
	}
	return nil
}

// EmbeddedPFlagHooks returns the pflag hooks for Embedded.
func EmbeddedPFlagHooks() cpflag.Hooks[Embedded] {
	return cpflag.Hooks[Embedded]{
		Apply:    embeddedApplyPFlags,
		Register: embeddedRegisterPFlags,
	}
}

func embeddedRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{strings.Join([]string{"region"}, o.Separator), strings.Join([]string{"zone"}, o.Separator)}
	for i, name := range names {
		if fs.Lookup(name) != nil || slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "us-east-1", "")
	fs.String(names[1], "a", "")
	return nil
}

func embeddedApplyPFlags(cfg *Embedded, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"region"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "region",
				Source: "--" + n,
			}
		}
		cfg.Base.Region = v
		set("region", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"zone"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "zone",
				Source: "--" + n,
			}
		}
		cfg.Zone = v
		set("zone", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *embeddedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "region":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Region = &str
			default:
				return fmt.Errorf("region: expected a string, got %v", v.Kind())
			}
		case "zone":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Zone = &str
			default:
				return fmt.Errorf("zone: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*embeddedShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Embedded) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "region = %v\n", c.Base.Region)
	fmt.Fprintf(&b, "zone = %v\n", c.Zone)
	return b.String()
}
