// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strings"
)

type embeddedShadow struct {
	Region *string `json:"region" toml:"region" yaml:"region"`
	Zone   *string `json:"zone" toml:"zone" yaml:"zone"`
}

// EmbeddedSchema returns the generated schema for Embedded.
func EmbeddedSchema() *configulator.Schema[Embedded] {
	return &configulator.Schema[Embedded]{
		ApplyDefaults: embeddedApplyDefaults,
		ApplyEnv:      embeddedApplyEnv,
		DecodeFile:    embeddedDecodeFile,
	}
}
func embeddedApplyDefaults(cfg *Embedded, set configulator.SetOrigin) error {
	cfg.Base.Region = "us-east-1"
	set("region", configulator.LayerDefault, "default tag")
	cfg.Zone = "a"
	set("zone", configulator.LayerDefault, "default tag")
	return nil
}
func embeddedDecodeFile(data []byte, u configulator.Unmarshal, cfg *Embedded, set configulator.SetOrigin, file string) error {
	var sh embeddedShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *embeddedShadow) applyTo(cfg *Embedded, set configulator.SetOrigin, file string) error {
	if s.Region != nil {
		cfg.Base.Region = *s.Region
		set("region", configulator.LayerFile, file)
	}
	if s.Zone != nil {
		cfg.Zone = *s.Zone
		set("zone", configulator.LayerFile, file)
	}
	return nil
}
func embeddedApplyEnv(cfg *Embedded, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "region"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Base.Region = v
			set("region", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "zone"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Zone = v
			set("zone", configulator.LayerEnv, n)
		}
	}
	return nil
}

// EmbeddedPFlagHooks returns the pflag hooks for Embedded.
func EmbeddedPFlagHooks() cpflag.Hooks[Embedded] {
	return cpflag.Hooks[Embedded]{
		Apply:    embeddedApplyPFlags,
		Register: embeddedRegisterPFlags,
	}
}
func embeddedRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"region"}, o.Separator), strings.Join([]string{"zone"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"region"}, o.Separator), "us-east-1", "")
	fs.String(strings.Join([]string{"zone"}, o.Separator), "a", "")
	return nil
}
func embeddedApplyPFlags(cfg *Embedded, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"region"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "region",
				Source: "--" + n,
			}
		}
		cfg.Base.Region = v
		set("region", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"zone"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "zone",
				Source: "--" + n,
			}
		}
		cfg.Zone = v
		set("zone", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *embeddedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "region":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Region = &str
			default:
				return fmt.Errorf("region: expected a string, got %v", v.Kind())
			}
		case "zone":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Zone = &str
			default:
				return fmt.Errorf("zone: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*embeddedShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Embedded) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("region = %v\n", c.Base.Region))
	b.WriteString(fmt.Sprintf("zone = %v\n", c.Zone))
	return b.String()
}
