// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type embeddedShadow struct {
	Region *string `json:"region" toml:"region" yaml:"region"`
	Zone   *string `json:"zone"   toml:"zone"   yaml:"zone"`
}

// EmbeddedSchema returns the generated schema for Embedded.
func EmbeddedSchema() *configulator.Schema[Embedded] {
	return &configulator.Schema[Embedded]{
		ApplyDefaults: embeddedApplyDefaults,
		ApplyEnv:      embeddedApplyEnv,
		DecodeFile:    embeddedDecodeFile,
	}
}

func embeddedApplyDefaults(cfg *Embedded, _ string, set configulator.SetOrigin) error {
	cfg.Region = "us-east-1"
	set("region", configulator.LayerDefault, "default tag")
	cfg.Zone = "a"
	set("zone", configulator.LayerDefault, "default tag")
	return nil
}

func embeddedDecodeFile(data []byte, u configulator.Unmarshal, cfg *Embedded, sep string, set configulator.SetOrigin, file string) error {
	var sh embeddedShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *embeddedShadow) applyTo(cfg *Embedded, _ string, set configulator.SetOrigin, file string) error {
	if s.Region != nil {
		cfg.Region = *s.Region
		set("region", configulator.LayerFile, file)
	}
	if s.Zone != nil {
		cfg.Zone = *s.Zone
		set("zone", configulator.LayerFile, file)
	}
	return nil
}

func embeddedApplyEnv(cfg *Embedded, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "region"); ok {
		cfg.Region = v
		set("region", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "zone"); ok {
		cfg.Zone = v
		set("zone", configulator.LayerEnv, n)
	}
	return nil
}

// EmbeddedPFlagHooks returns the pflag hooks for Embedded.
func EmbeddedPFlagHooks() cpflag.Hooks[Embedded] {
	return cpflag.Hooks[Embedded]{
		Apply:    embeddedApplyPFlags,
		Register: embeddedRegisterPFlags,
	}
}

func embeddedRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"region",
		"zone",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "us-east-1", "")
	fs.String(names[1], "a", "")
	return nil
}

func embeddedApplyPFlags(cfg *Embedded, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "region"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "region",
				Source: "--" + n,
			}
		}
		cfg.Region = v
		set("region", configulator.LayerCLI, "--"+n)
	}
	if n := "zone"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "zone",
				Source: "--" + n,
			}
		}
		cfg.Zone = v
		set("zone", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *embeddedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "region":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Region = &str
			default:
				return embeddedJSONError("region", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "zone":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Zone = &str
			default:
				return embeddedJSONError("zone", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: embeddedQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*embeddedShadow)(nil)

// embeddedJSONError returns a ParseError for the JSON token v at path.
func embeddedJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Embedded) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "region = %v\n", c.Region)
	fmt.Fprintf(&b, "zone = %v\n", c.Zone)
	return b.String()
}

func embeddedQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
