// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"strconv"
	"strings"
)

type nHTTPShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}
type nPoolShadow struct {
	Size *uint16 `json:"size" toml:"size" yaml:"size"`
}
type nDBShadow struct {
	URL  *string      `json:"url" toml:"url" yaml:"url"`
	Pool *nPoolShadow `json:"pool" toml:"pool" yaml:"pool"`
}
type nestedShadow struct {
	AppName *string      `json:"app-name" toml:"app-name" yaml:"app-name"`
	HTTP    *nHTTPShadow `json:"http" toml:"http" yaml:"http"`
	DB      *nDBShadow   `json:"db" toml:"db" yaml:"db"`
}

// NestedSchema returns the generated schema for Nested.
func NestedSchema() *configulator.Schema[Nested] {
	return &configulator.Schema[Nested]{
		ApplyDefaults: nestedApplyDefaults,
		ApplyEnv:      nestedApplyEnv,
		DecodeFile:    nestedDecodeFile,
	}
}
func nestedApplyDefaults(cfg *Nested, set configulator.SetOrigin) error {
	cfg.AppName = "myapp"
	set("app-name", configulator.LayerDefault, "default tag")
	cfg.HTTP.Host = "localhost"
	set("http.host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.DB.URL = "postgres://localhost/db"
	set("db.url", configulator.LayerDefault, "default tag")
	cfg.DB.Pool.Size = uint16(10)
	set("db.pool.size", configulator.LayerDefault, "default tag")
	return nil
}
func nestedDecodeFile(data []byte, u configulator.Unmarshal, cfg *Nested, set configulator.SetOrigin, file string) error {
	var sh nestedShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *nestedShadow) applyTo(cfg *Nested, set configulator.SetOrigin, file string) error {
	if s.AppName != nil {
		cfg.AppName = *s.AppName
		set("app-name", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Host != nil {
			cfg.HTTP.Host = *s.HTTP.Host
			set("http.host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.DB != nil {
		if s.DB.URL != nil {
			cfg.DB.URL = *s.DB.URL
			set("db.url", configulator.LayerFile, file)
		}
		if s.DB.Pool != nil {
			if s.DB.Pool.Size != nil {
				cfg.DB.Pool.Size = *s.DB.Pool.Size
				set("db.pool.size", configulator.LayerFile, file)
			}
		}
	}
	return nil
}
func nestedApplyEnv(cfg *Nested, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "app-name"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.AppName = v
			set("app-name", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Host = v
			set("http.host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = uint16(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "db", "url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.DB.URL = v
			set("db.url", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "db", "pool", "size"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "db.pool.size",
					Source: n,
					Value:  v,
				}
			}
			cfg.DB.Pool.Size = uint16(p)
			set("db.pool.size", configulator.LayerEnv, n)
		}
	}
	return nil
}

// NestedPFlagHooks returns the pflag hooks for Nested.
func NestedPFlagHooks() cpflag.Hooks[Nested] {
	return cpflag.Hooks[Nested]{
		Apply:    nestedApplyPFlags,
		Register: nestedRegisterPFlags,
	}
}
func nestedRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"app-name"}, o.Separator), strings.Join([]string{"http", "host"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"db", "url"}, o.Separator), strings.Join([]string{"db", "pool", "size"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"app-name"}, o.Separator), "myapp", "")
	fs.String(strings.Join([]string{"http", "host"}, o.Separator), "localhost", "")
	fs.Uint16(strings.Join([]string{"http", "port"}, o.Separator), uint16(8080), "")
	fs.String(strings.Join([]string{"db", "url"}, o.Separator), "postgres://localhost/db", "")
	fs.Uint16(strings.Join([]string{"db", "pool", "size"}, o.Separator), uint16(10), "")
	return nil
}
func nestedApplyPFlags(cfg *Nested, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"app-name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "app-name",
				Source: "--" + n,
			}
		}
		cfg.AppName = v
		set("app-name", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"db", "url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.url",
				Source: "--" + n,
			}
		}
		cfg.DB.URL = v
		set("db.url", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"db", "pool", "size"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.pool.size",
				Source: "--" + n,
			}
		}
		cfg.DB.Pool.Size = v
		set("db.pool.size", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *nestedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "app-name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.AppName = &str
			default:
				return fmt.Errorf("app-name: expected a string, got %v", v.Kind())
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub nHTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "db":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub nDBShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.DB = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nestedShadow)(nil)

func (s *nHTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nHTTPShadow)(nil)

func (s *nDBShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.URL = &str
			default:
				return fmt.Errorf("url: expected a string, got %v", v.Kind())
			}
		case "pool":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub nPoolShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Pool = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nDBShadow)(nil)

func (s *nPoolShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("size: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Size = &val
			default:
				return fmt.Errorf("size: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nPoolShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Nested) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("app-name = %v\n", c.AppName))
	b.WriteString(fmt.Sprintf("http.host = %v\n", c.HTTP.Host))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	b.WriteString(fmt.Sprintf("db.url = %v\n", c.DB.URL))
	b.WriteString(fmt.Sprintf("db.pool.size = %v\n", c.DB.Pool.Size))
	return b.String()
}
