// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
)

type nHTTPShadow struct {
	Host *string `json:"host" toml:"host" yaml:"host"`
	Port *uint16 `json:"port" toml:"port" yaml:"port"`
}

type nPoolShadow struct {
	Size *uint16 `json:"size" toml:"size" yaml:"size"`
}

type nDBShadow struct {
	URL  *string      `json:"url"  toml:"url"  yaml:"url"`
	Pool *nPoolShadow `json:"pool" toml:"pool" yaml:"pool"`
}

type nestedShadow struct {
	AppName *string      `json:"app-name" toml:"app-name" yaml:"app-name"`
	HTTP    *nHTTPShadow `json:"http"     toml:"http"     yaml:"http"`
	DB      *nDBShadow   `json:"db"       toml:"db"       yaml:"db"`
}

// NestedSchema returns the generated schema for Nested.
func NestedSchema() *configulator.Schema[Nested] {
	return &configulator.Schema[Nested]{
		ApplyDefaults: nestedApplyDefaults,
		ApplyEnv:      nestedApplyEnv,
		DecodeFile:    nestedDecodeFile,
	}
}

func nestedApplyDefaults(cfg *Nested, _ string, set configulator.SetOrigin) error {
	cfg.AppName = "myapp"
	set("app-name", configulator.LayerDefault, "default tag")
	cfg.HTTP.Host = "localhost"
	set("http.host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.DB.URL = "postgres://localhost/db"
	set("db.url", configulator.LayerDefault, "default tag")
	cfg.DB.Pool.Size = uint16(10)
	set("db.pool.size", configulator.LayerDefault, "default tag")
	return nil
}

func nestedDecodeFile(data []byte, u configulator.Unmarshal, cfg *Nested, sep string, set configulator.SetOrigin, file string) error {
	var sh nestedShadow
	if err := u(data, &sh); err != nil {
		return configulator.NewDecodeError(file, err)
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *nestedShadow) applyTo(cfg *Nested, _ string, set configulator.SetOrigin, file string) error {
	if s.AppName != nil {
		cfg.AppName = *s.AppName
		set("app-name", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Host != nil {
			cfg.HTTP.Host = *s.HTTP.Host
			set("http.host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.DB != nil {
		if s.DB.URL != nil {
			cfg.DB.URL = *s.DB.URL
			set("db.url", configulator.LayerFile, file)
		}
		if s.DB.Pool != nil {
			if s.DB.Pool.Size != nil {
				cfg.DB.Pool.Size = *s.DB.Pool.Size
				set("db.pool.size", configulator.LayerFile, file)
			}
		}
	}
	return nil
}

func nestedApplyEnv(cfg *Nested, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("app-name"); ok {
		cfg.AppName = v
		set("app-name", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "host"); ok {
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("db", "url"); ok {
		cfg.DB.URL = v
		set("db.url", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("db", "pool", "size"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.pool.size",
				Source: n,
				Value:  v,
			}
		}
		cfg.DB.Pool.Size = uint16(p)
		set("db.pool.size", configulator.LayerEnv, n)
	}
	return nil
}

// NestedPFlagHooks returns the pflag hooks for Nested.
func NestedPFlagHooks() cpflag.Hooks[Nested] {
	return cpflag.Hooks[Nested]{
		Apply:    nestedApplyPFlags,
		Register: nestedRegisterPFlags,
	}
}

func nestedRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"app-name",
		"http" + o.Separator + "host",
		"http" + o.Separator + "port",
		"db" + o.Separator + "url",
		"db" + o.Separator + "pool" + o.Separator + "size",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "myapp", "")
	fs.String(names[1], "localhost", "")
	fs.Uint16(names[2], 8080, "")
	fs.String(names[3], "postgres://localhost/db", "")
	fs.Uint16(names[4], 10, "")
	return nil
}

func nestedApplyPFlags(cfg *Nested, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "app-name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "app-name",
				Source: "--" + n,
			}
		}
		cfg.AppName = v
		set("app-name", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Host = v
		set("http.host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "db" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.url",
				Source: "--" + n,
			}
		}
		cfg.DB.URL = v
		set("db.url", configulator.LayerCLI, "--"+n)
	}
	if n := "db" + o.Separator + "pool" + o.Separator + "size"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "db.pool.size",
				Source: "--" + n,
			}
		}
		cfg.DB.Pool.Size = v
		set("db.pool.size", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *nestedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "app-name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.AppName = &str
			default:
				return nestedJSONError("app-name", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return nestedJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub nHTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "db":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return nestedJSONError("db", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub nDBShadow
				if err := sub.decodeJSON(dec, "db"); err != nil {
					return err
				}
				s.DB = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: nestedQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*nestedShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *nHTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return nestedJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return nestedJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return nestedJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return nestedJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + nestedQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *nDBShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return nestedJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "pool":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return nestedJSONError(path+".pool", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub nPoolShadow
				if err := sub.decodeJSON(dec, path+".pool"); err != nil {
					return err
				}
				s.Pool = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + nestedQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *nPoolShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return nestedJSONError(path+".size", v, err)
				}
				if raw > math.MaxUint16 {
					return nestedJSONError(path+".size", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Size = &num
			default:
				return nestedJSONError(path+".size", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + nestedQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// nestedJSONError returns a ParseError for the JSON token v at path.
func nestedJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Nested) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "app-name = %v\n", c.AppName)
	fmt.Fprintf(&b, "http.host = %v\n", c.HTTP.Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "db.url = %v\n", c.DB.URL)
	fmt.Fprintf(&b, "db.pool.size = %v\n", c.DB.Pool.Size)
	return b.String()
}

func nestedQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
