// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type nCRuleShadow struct {
	From  *int64 `json:"from" toml:"from" yaml:"from"`
	Range *int64 `json:"range" toml:"range" yaml:"range"`
	On    *bool  `json:"on" toml:"on" yaml:"on"`
}
type nCLevelShadow struct {
	Level *int64 `json:"level" toml:"level" yaml:"level"`
}
type nCPeerShadow struct {
	Name  *string                  `json:"name" toml:"name" yaml:"name"`
	Slots *int64                   `json:"slots" toml:"slots" yaml:"slots"`
	Rules *[]nCRuleShadow          `json:"rules" toml:"rules" yaml:"rules"`
	Tags  *map[string]nCRuleShadow `json:"tags" toml:"tags" yaml:"tags"`
	Inner *nCLevelShadow           `json:"inner" toml:"inner" yaml:"inner"`
	Opt   *nCLevelShadow           `json:"opt" toml:"opt" yaml:"opt"`
}
type nestedCollectionsShadow struct {
	Peers  *[]nCPeerShadow          `json:"peers" toml:"peers" yaml:"peers"`
	ByName *map[string]nCPeerShadow `json:"by-name" toml:"by-name" yaml:"by-name"`
}

// NestedCollectionsSchema returns the generated schema for NestedCollections.
func NestedCollectionsSchema() *configulator.Schema[NestedCollections] {
	return &configulator.Schema[NestedCollections]{
		ApplyDefaults: nestedCollectionsApplyDefaults,
		ApplyEnv:      nestedCollectionsApplyEnv,
		DecodeFile:    nestedCollectionsDecodeFile,
	}
}
func nestedCollectionsApplyDefaults(cfg *NestedCollections, sep string, set configulator.SetOrigin) error {
	return nil
}
func nestedCollectionsDecodeFile(data []byte, u configulator.Unmarshal, cfg *NestedCollections, sep string, set configulator.SetOrigin, file string) error {
	var sh nestedCollectionsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}
func (s *nestedCollectionsShadow) applyTo(cfg *NestedCollections, sep string, set configulator.SetOrigin, file string) error {
	if s.Peers != nil {
		out := make([]NCPeer, len(*s.Peers))
		for i, esh := range *s.Peers {
			var e NCPeer
			idx := "peers[" + strconv.Itoa(i) + "]"
			e.Slots = int64(3)
			set(idx+".slots", configulator.LayerDefault, "element default")
			e.Inner.Level = int64(7)
			set(idx+".inner.level", configulator.LayerDefault, "element default")
			if esh.Name != nil {
				e.Name = *esh.Name
				set(idx+".name", configulator.LayerFile, file)
			}
			if esh.Slots != nil {
				e.Slots = *esh.Slots
				set(idx+".slots", configulator.LayerFile, file)
			}
			if esh.Rules != nil {
				out1 := make([]NCRule, len(*esh.Rules))
				for i1, esh1 := range *esh.Rules {
					var e1 NCRule
					idx1 := idx + ".rules[" + strconv.Itoa(i1) + "]"
					e1.Range = int64(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					e1.On = true
					set(idx1+".on", configulator.LayerDefault, "element default")
					if esh1.From != nil {
						e1.From = *esh1.From
						set(idx1+".from", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					if esh1.On != nil {
						e1.On = *esh1.On
						set(idx1+".on", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.Rules = out1
				set(idx+".rules", configulator.LayerFile, file)
			}
			if esh.Tags != nil {
				out1 := make(map[string]NCRule, len(*esh.Tags))
				for k1, esh1 := range *esh.Tags {
					var e1 NCRule
					key1 := idx + ".tags." + nestedCollectionsQuoteKey(k1)
					e1.Range = int64(1)
					set(key1+".range", configulator.LayerDefault, "element default")
					e1.On = true
					set(key1+".on", configulator.LayerDefault, "element default")
					if esh1.From != nil {
						e1.From = *esh1.From
						set(key1+".from", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(key1+".range", configulator.LayerFile, file)
					}
					if esh1.On != nil {
						e1.On = *esh1.On
						set(key1+".on", configulator.LayerFile, file)
					}
					out1[k1] = e1
				}
				e.Tags = out1
				set(idx+".tags", configulator.LayerFile, file)
			}
			if esh.Inner != nil {
				if esh.Inner.Level != nil {
					e.Inner.Level = *esh.Inner.Level
					set(idx+".inner.level", configulator.LayerFile, file)
				}
			}
			if esh.Opt != nil {
				e1 := NCLevel{}
				e1.Level = int64(7)
				set(idx+".opt.level", configulator.LayerDefault, "element default")
				if e.Opt != nil {
					e1 = *e.Opt
				}
				if esh.Opt.Level != nil {
					e1.Level = *esh.Opt.Level
					set(idx+".opt.level", configulator.LayerFile, file)
				}
				e.Opt = &e1
			}
			out[i] = e
		}
		cfg.Peers = out
		set("peers", configulator.LayerFile, file)
	}
	if s.ByName != nil {
		out := make(map[string]NCPeer, len(*s.ByName))
		for k, esh := range *s.ByName {
			var e NCPeer
			key := "by-name." + nestedCollectionsQuoteKey(k)
			e.Slots = int64(3)
			set(key+".slots", configulator.LayerDefault, "element default")
			e.Inner.Level = int64(7)
			set(key+".inner.level", configulator.LayerDefault, "element default")
			if esh.Name != nil {
				e.Name = *esh.Name
				set(key+".name", configulator.LayerFile, file)
			}
			if esh.Slots != nil {
				e.Slots = *esh.Slots
				set(key+".slots", configulator.LayerFile, file)
			}
			if esh.Rules != nil {
				out1 := make([]NCRule, len(*esh.Rules))
				for i1, esh1 := range *esh.Rules {
					var e1 NCRule
					idx1 := key + ".rules[" + strconv.Itoa(i1) + "]"
					e1.Range = int64(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					e1.On = true
					set(idx1+".on", configulator.LayerDefault, "element default")
					if esh1.From != nil {
						e1.From = *esh1.From
						set(idx1+".from", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					if esh1.On != nil {
						e1.On = *esh1.On
						set(idx1+".on", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.Rules = out1
				set(key+".rules", configulator.LayerFile, file)
			}
			if esh.Tags != nil {
				out1 := make(map[string]NCRule, len(*esh.Tags))
				for k1, esh1 := range *esh.Tags {
					var e1 NCRule
					key1 := key + ".tags." + nestedCollectionsQuoteKey(k1)
					e1.Range = int64(1)
					set(key1+".range", configulator.LayerDefault, "element default")
					e1.On = true
					set(key1+".on", configulator.LayerDefault, "element default")
					if esh1.From != nil {
						e1.From = *esh1.From
						set(key1+".from", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(key1+".range", configulator.LayerFile, file)
					}
					if esh1.On != nil {
						e1.On = *esh1.On
						set(key1+".on", configulator.LayerFile, file)
					}
					out1[k1] = e1
				}
				e.Tags = out1
				set(key+".tags", configulator.LayerFile, file)
			}
			if esh.Inner != nil {
				if esh.Inner.Level != nil {
					e.Inner.Level = *esh.Inner.Level
					set(key+".inner.level", configulator.LayerFile, file)
				}
			}
			if esh.Opt != nil {
				e1 := NCLevel{}
				e1.Level = int64(7)
				set(key+".opt.level", configulator.LayerDefault, "element default")
				if e.Opt != nil {
					e1 = *e.Opt
				}
				if esh.Opt.Level != nil {
					e1.Level = *esh.Opt.Level
					set(key+".opt.level", configulator.LayerFile, file)
				}
				e.Opt = &e1
			}
			out[k] = e
		}
		cfg.ByName = out
		set("by-name", configulator.LayerFile, file)
	}
	return nil
}
func nestedCollectionsApplyEnv(cfg *NestedCollections, ec configulator.EnvContext, set configulator.SetOrigin) error {
	return nil
}

// NestedCollectionsPFlagHooks returns the pflag hooks for NestedCollections.
func NestedCollectionsPFlagHooks() cpflag.Hooks[NestedCollections] {
	return cpflag.Hooks[NestedCollections]{
		Apply:    nestedCollectionsApplyPFlags,
		Register: nestedCollectionsRegisterPFlags,
	}
}
func nestedCollectionsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	return nil
}
func nestedCollectionsApplyPFlags(cfg *NestedCollections, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	return nil
}
func (s *nestedCollectionsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "peers":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("peers: expected an array, got %v", tok.Kind())
				}
				out := []nCPeerShadow{}
				for dec.PeekKind() != ']' {
					var el nCPeerShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Peers = &out
			}
		case "by-name":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '{' {
					return fmt.Errorf("by-name: expected an object, got %v", tok.Kind())
				}
				out := map[string]nCPeerShadow{}
				for dec.PeekKind() != '}' {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					mk := kt.String()
					var el nCPeerShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out[mk] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.ByName = &out
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nestedCollectionsShadow)(nil)

func (s *nCPeerShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "slots":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return fmt.Errorf("slots: %w", err)
				}
				val := num
				s.Slots = &val
			default:
				return fmt.Errorf("slots: expected a number, got %v", v.Kind())
			}
		case "rules":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("rules: expected an array, got %v", tok.Kind())
				}
				out := []nCRuleShadow{}
				for dec.PeekKind() != ']' {
					var el nCRuleShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Rules = &out
			}
		case "tags":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '{' {
					return fmt.Errorf("tags: expected an object, got %v", tok.Kind())
				}
				out := map[string]nCRuleShadow{}
				for dec.PeekKind() != '}' {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					mk := kt.String()
					var el nCRuleShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out[mk] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Tags = &out
			}
		case "inner":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub nCLevelShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Inner = &sub
			}
		case "opt":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub nCLevelShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Opt = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nCPeerShadow)(nil)

func (s *nCRuleShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "from":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return fmt.Errorf("from: %w", err)
				}
				val := num
				s.From = &val
			default:
				return fmt.Errorf("from: expected a number, got %v", v.Kind())
			}
		case "range":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return fmt.Errorf("range: %w", err)
				}
				val := num
				s.Range = &val
			default:
				return fmt.Errorf("range: expected a number, got %v", v.Kind())
			}
		case "on":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.On = &b
			default:
				return fmt.Errorf("on: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nCRuleShadow)(nil)

func (s *nCLevelShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return fmt.Errorf("level: %w", err)
				}
				val := num
				s.Level = &val
			default:
				return fmt.Errorf("level: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*nCLevelShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *NestedCollections) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("peers = %v\n", c.Peers))
	b.WriteString(fmt.Sprintf("by-name = %v\n", c.ByName))
	return b.String()
}
func nestedCollectionsQuoteKey(k string) string {
	for _, c := range k {
		if c == '.' || c == '[' {
			return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
		}
	}
	return k
}
