// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"strconv"
	"strings"
)

type tlsShadow struct {
	Cert       *string `json:"cert" toml:"cert" yaml:"cert"`
	MinVersion *uint16 `json:"min-version" toml:"min-version" yaml:"min-version"`
}
type optionalsShadow struct {
	Port *uint16    `json:"port" toml:"port" yaml:"port"`
	Name *string    `json:"name" toml:"name" yaml:"name"`
	TLS  *tlsShadow `json:"tls" toml:"tls" yaml:"tls"`
}

// OptionalsSchema returns the generated schema for Optionals.
func OptionalsSchema() *configulator.Schema[Optionals] {
	return &configulator.Schema[Optionals]{
		ApplyDefaults: optionalsApplyDefaults,
		ApplyEnv:      optionalsApplyEnv,
		DecodeFile:    optionalsDecodeFile,
	}
}
func optionalsApplyDefaults(cfg *Optionals, set configulator.SetOrigin) error {
	nameDefault := "opt-name"
	cfg.Name = &nameDefault
	set("name", configulator.LayerDefault, "default tag")
	return nil
}
func optionalsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Optionals, set configulator.SetOrigin, file string) error {
	var sh optionalsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *optionalsShadow) applyTo(cfg *Optionals, set configulator.SetOrigin, file string) error {
	if s.Port != nil {
		v := *s.Port // never alias the shadow
		cfg.Port = &v
		set("port", configulator.LayerFile, file)
	}
	if s.Name != nil {
		v := *s.Name // never alias the shadow
		cfg.Name = &v
		set("name", configulator.LayerFile, file)
	}
	if s.TLS != nil {
		e := Tls{}
		e.MinVersion = uint16(12)
		set("tls.min-version", configulator.LayerDefault, "element default")
		if cfg.TLS != nil {
			e = *cfg.TLS // deep-merge onto the existing value (cloned)
		}
		if s.TLS.Cert != nil {
			e.Cert = *s.TLS.Cert
			set("tls.cert", configulator.LayerFile, file)
		}
		if s.TLS.MinVersion != nil {
			e.MinVersion = *s.TLS.MinVersion
			set("tls.min-version", configulator.LayerFile, file)
		}
		cfg.TLS = &e
	}
	return nil
}
func optionalsApplyEnv(cfg *Optionals, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			pv := uint16(p)
			cfg.Port = &pv // allocate-on-set (SPEC rule 5)
			set("port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "name"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Name = &v // allocate-on-set (SPEC rule 5)
			set("name", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "tls", "cert"); true {
		if v, ok := ec.Getenv(n); ok {
			var e Tls
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.Cert = v
			cfg.TLS = &e
			set("tls.cert", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "tls", "min-version"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "tls.min-version",
					Source: n,
					Value:  v,
				}
			}
			var e Tls
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.MinVersion = uint16(p)
			cfg.TLS = &e
			set("tls.min-version", configulator.LayerEnv, n)
		}
	}
	return nil
}

// OptionalsPFlagHooks returns the pflag hooks for Optionals.
func OptionalsPFlagHooks() cpflag.Hooks[Optionals] {
	return cpflag.Hooks[Optionals]{
		Apply:    optionalsApplyPFlags,
		Register: optionalsRegisterPFlags,
	}
}
func optionalsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"name"}, o.Separator), strings.Join([]string{"tls"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.Uint16(strings.Join([]string{"port"}, o.Separator), uint16(0), "")
	fs.String(strings.Join([]string{"name"}, o.Separator), "", "")
	// tls: no pflag registration (unsupported flag kind)
	return nil
}
func optionalsApplyPFlags(cfg *Optionals, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = &v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "name",
				Source: "--" + n,
			}
		}
		cfg.Name = &v
		set("name", configulator.LayerCLI, "--"+n)
	}
	// tls: no pflag apply (unsupported flag kind)
	return nil
}
func (s *optionalsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "tls":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub tlsShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.TLS = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*optionalsShadow)(nil)

func (s *tlsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "cert":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Cert = &str
			default:
				return fmt.Errorf("cert: expected a string, got %v", v.Kind())
			}
		case "min-version":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("min-version: %d overflows uint16", num)
				}
				val := uint16(num)
				s.MinVersion = &val
			default:
				return fmt.Errorf("min-version: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*tlsShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Optionals) PrintConfig() string {
	var b strings.Builder
	if c.Port == nil {
		b.WriteString("port = <unset>\n")
	} else {
		b.WriteString(fmt.Sprintf("port = %v\n", *c.Port))
	}
	if c.Name == nil {
		b.WriteString("name = <unset>\n")
	} else {
		b.WriteString(fmt.Sprintf("name = %v\n", *c.Name))
	}
	if c.TLS == nil {
		b.WriteString("tls = <unset>\n")
	} else {
		b.WriteString(fmt.Sprintf("tls = %v\n", *c.TLS))
	}
	return b.String()
}
