// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type tLSConfigShadow struct {
	Cert       *string `json:"cert"        toml:"cert"        yaml:"cert"`
	MinVersion *uint16 `json:"min-version" toml:"min-version" yaml:"min-version"`
}

type optionalsShadow struct {
	Port *uint16          `json:"port" toml:"port" yaml:"port"`
	Name *string          `json:"name" toml:"name" yaml:"name"`
	TLS  *tLSConfigShadow `json:"tls"  toml:"tls"  yaml:"tls"`
}

// OptionalsSchema returns the generated schema for Optionals.
func OptionalsSchema() *configulator.Schema[Optionals] {
	return &configulator.Schema[Optionals]{
		ApplyDefaults: optionalsApplyDefaults,
		ApplyEnv:      optionalsApplyEnv,
		DecodeFile:    optionalsDecodeFile,
	}
}

func optionalsApplyDefaults(cfg *Optionals, _ string, set configulator.SetOrigin) error {
	{
		nameDefault := "opt-name"
		cfg.Name = &nameDefault
		set("name", configulator.LayerDefault, "default tag")
	}
	return nil
}

func optionalsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Optionals, sep string, set configulator.SetOrigin, file string) error {
	var sh optionalsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *optionalsShadow) applyTo(cfg *Optionals, _ string, set configulator.SetOrigin, file string) error {
	if s.Port != nil {
		v := *s.Port
		cfg.Port = &v
		set("port", configulator.LayerFile, file)
	}
	if s.Name != nil {
		v := *s.Name
		cfg.Name = &v
		set("name", configulator.LayerFile, file)
	}
	if s.TLS != nil {
		e := TLSConfig{}
		e.MinVersion = uint16(12)
		set("tls.min-version", configulator.LayerDefault, "element default")
		if cfg.TLS != nil {
			e = *cfg.TLS
		}
		if s.TLS.Cert != nil {
			e.Cert = *s.TLS.Cert
			set("tls.cert", configulator.LayerFile, file)
		}
		if s.TLS.MinVersion != nil {
			e.MinVersion = *s.TLS.MinVersion
			set("tls.min-version", configulator.LayerFile, file)
		}
		cfg.TLS = &e
	}
	return nil
}

func optionalsApplyEnv(cfg *Optionals, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		pv := uint16(p)
		cfg.Port = &pv
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "name"); ok {
		pv := v
		cfg.Name = &pv
		set("name", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "tls", "cert"); ok {
		var e TLSConfig
		if cfg.TLS != nil {
			e = *cfg.TLS
		} else {
			e.MinVersion = uint16(12)
			set("tls.min-version", configulator.LayerDefault, "element default")
		}
		e.Cert = v
		cfg.TLS = &e
		set("tls.cert", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "tls", "min-version"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.min-version",
				Source: n,
				Value:  v,
			}
		}
		var e TLSConfig
		if cfg.TLS != nil {
			e = *cfg.TLS
		} else {
			e.MinVersion = uint16(12)
			set("tls.min-version", configulator.LayerDefault, "element default")
		}
		e.MinVersion = uint16(p)
		cfg.TLS = &e
		set("tls.min-version", configulator.LayerEnv, n)
	}
	return nil
}

// OptionalsPFlagHooks returns the pflag hooks for Optionals.
func OptionalsPFlagHooks() cpflag.Hooks[Optionals] {
	return cpflag.Hooks[Optionals]{
		Apply:    optionalsApplyPFlags,
		Register: optionalsRegisterPFlags,
	}
}

func optionalsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"port",
		"name",
		"tls" + o.Separator + "cert",
		"tls" + o.Separator + "min-version",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.Uint16(names[0], 0, "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.Uint16(names[3], 12, "")
	return nil
}

func optionalsApplyPFlags(cfg *Optionals, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		pv := v
		cfg.Port = &pv
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := "name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "name",
				Source: "--" + n,
			}
		}
		pv := v
		cfg.Name = &pv
		set("name", configulator.LayerCLI, "--"+n)
	}
	if n := "tls" + o.Separator + "cert"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.cert",
				Source: "--" + n,
			}
		}
		var e TLSConfig
		if cfg.TLS != nil {
			e = *cfg.TLS
		} else {
			e.MinVersion = uint16(12)
			set("tls.min-version", configulator.LayerDefault, "element default")
		}
		e.Cert = v
		cfg.TLS = &e
		set("tls.cert", configulator.LayerCLI, "--"+n)
	}
	if n := "tls" + o.Separator + "min-version"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.min-version",
				Source: "--" + n,
			}
		}
		var e TLSConfig
		if cfg.TLS != nil {
			e = *cfg.TLS
		} else {
			e.MinVersion = uint16(12)
			set("tls.min-version", configulator.LayerDefault, "element default")
		}
		e.MinVersion = v
		cfg.TLS = &e
		set("tls.min-version", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *optionalsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return optionalsJSONError("port", v, err)
				}
				if raw > math.MaxUint16 {
					return optionalsJSONError("port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return optionalsJSONError("port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Name = &str
			default:
				return optionalsJSONError("name", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "tls":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return optionalsJSONError("tls", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub tLSConfigShadow
				if err := sub.decodeJSON(dec, "tls"); err != nil {
					return err
				}
				s.TLS = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: optionalsQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*optionalsShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *tLSConfigShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "cert":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Cert = &str
			default:
				return optionalsJSONError(path+".cert", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "min-version":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return optionalsJSONError(path+".min-version", v, err)
				}
				if raw > math.MaxUint16 {
					return optionalsJSONError(path+".min-version", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.MinVersion = &num
			default:
				return optionalsJSONError(path+".min-version", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + optionalsQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// optionalsJSONError returns a ParseError for the JSON token v at path.
func optionalsJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Optionals) PrintConfig() string {
	var b strings.Builder
	if c.Port == nil {
		b.WriteString("port = <unset>\n")
	} else {
		fmt.Fprintf(&b, "port = %v\n", *c.Port)
	}
	if c.Name == nil {
		b.WriteString("name = <unset>\n")
	} else {
		fmt.Fprintf(&b, "name = %v\n", *c.Name)
	}
	if p := c.TLS; p == nil {
		b.WriteString("tls = <unset>\n")
	} else {
		fmt.Fprintf(&b, "tls.cert = %v\n", p.Cert)
		fmt.Fprintf(&b, "tls.min-version = %v\n", p.MinVersion)
	}
	return b.String()
}

func optionalsQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
