// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
)

type tLSConfigShadow struct {
	Cert       *string `json:"cert" toml:"cert" yaml:"cert"`
	MinVersion *uint16 `json:"min-version" toml:"min-version" yaml:"min-version"`
}

type optionalsShadow struct {
	Port *uint16          `json:"port" toml:"port" yaml:"port"`
	Name *string          `json:"name" toml:"name" yaml:"name"`
	TLS  *tLSConfigShadow `json:"tls" toml:"tls" yaml:"tls"`
}

// OptionalsSchema returns the generated schema for Optionals.
func OptionalsSchema() *configulator.Schema[Optionals] {
	return &configulator.Schema[Optionals]{
		ApplyDefaults: optionalsApplyDefaults,
		ApplyEnv:      optionalsApplyEnv,
		DecodeFile:    optionalsDecodeFile,
	}
}

func optionalsApplyDefaults(cfg *Optionals, sep string, set configulator.SetOrigin) error {
	{
		nameDefault := "opt-name"
		cfg.Name = &nameDefault
		set("name", configulator.LayerDefault, "default tag")
	}
	return nil
}

func optionalsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Optionals, sep string, set configulator.SetOrigin, file string) error {
	var sh optionalsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *optionalsShadow) applyTo(cfg *Optionals, sep string, set configulator.SetOrigin, file string) error {
	if s.Port != nil {
		v := *s.Port
		cfg.Port = &v
		set("port", configulator.LayerFile, file)
	}
	if s.Name != nil {
		v := *s.Name
		cfg.Name = &v
		set("name", configulator.LayerFile, file)
	}
	if s.TLS != nil {
		e := TLSConfig{}
		e.MinVersion = uint16(12)
		set("tls.min-version", configulator.LayerDefault, "element default")
		if cfg.TLS != nil {
			e = *cfg.TLS
		}
		if s.TLS.Cert != nil {
			e.Cert = *s.TLS.Cert
			set("tls.cert", configulator.LayerFile, file)
		}
		if s.TLS.MinVersion != nil {
			e.MinVersion = *s.TLS.MinVersion
			set("tls.min-version", configulator.LayerFile, file)
		}
		cfg.TLS = &e
	}
	return nil
}

func optionalsApplyEnv(cfg *Optionals, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		pv := uint16(p)
		cfg.Port = &pv
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("name"); ok {
		pv := v
		cfg.Name = &pv
		set("name", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("tls", "cert"); ok {
		{
			var e TLSConfig
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.Cert = v
			cfg.TLS = &e
		}
		set("tls.cert", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("tls", "min-version"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.min-version",
				Source: n,
				Value:  v,
			}
		}
		{
			var e TLSConfig
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.MinVersion = uint16(p)
			cfg.TLS = &e
		}
		set("tls.min-version", configulator.LayerEnv, n)
	}
	return nil
}

// OptionalsPFlagHooks returns the pflag hooks for Optionals.
func OptionalsPFlagHooks() cpflag.Hooks[Optionals] {
	return cpflag.Hooks[Optionals]{
		Apply:    optionalsApplyPFlags,
		Register: optionalsRegisterPFlags,
	}
}

func optionalsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"name"}, o.Separator), strings.Join([]string{"tls", "cert"}, o.Separator), strings.Join([]string{"tls", "min-version"}, o.Separator)}
	for i, name := range names {
		if fs.Lookup(name) != nil || slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.Uint16(names[0], 0, "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.Uint16(names[3], uint16(12), "")
	return nil
}

func optionalsApplyPFlags(cfg *Optionals, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		pv := v
		cfg.Port = &pv
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "name",
				Source: "--" + n,
			}
		}
		pv := v
		cfg.Name = &pv
		set("name", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"tls", "cert"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.cert",
				Source: "--" + n,
			}
		}
		{
			var e TLSConfig
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.Cert = v
			cfg.TLS = &e
		}
		set("tls.cert", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"tls", "min-version"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "tls.min-version",
				Source: "--" + n,
			}
		}
		{
			var e TLSConfig
			if cfg.TLS != nil {
				e = *cfg.TLS
			} else {
				e.MinVersion = uint16(12)
				set("tls.min-version", configulator.LayerDefault, "element default")
			}
			e.MinVersion = v
			cfg.TLS = &e
		}
		set("tls.min-version", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *optionalsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("port: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "tls":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub tLSConfigShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.TLS = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*optionalsShadow)(nil)

func (s *tLSConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "cert":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Cert = &str
			default:
				return fmt.Errorf("cert: expected a string, got %v", v.Kind())
			}
		case "min-version":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("min-version: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("min-version: %d overflows uint16", num)
				}
				val := uint16(num)
				s.MinVersion = &val
			default:
				return fmt.Errorf("min-version: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*tLSConfigShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Optionals) PrintConfig() string {
	var b strings.Builder
	if c.Port == nil {
		b.WriteString("port = <unset>\n")
	} else {
		fmt.Fprintf(&b, "port = %v\n", *c.Port)
	}
	if c.Name == nil {
		b.WriteString("name = <unset>\n")
	} else {
		fmt.Fprintf(&b, "name = %v\n", *c.Name)
	}
	if p := c.TLS; p == nil {
		b.WriteString("tls = <unset>\n")
	} else {
		fmt.Fprintf(&b, "tls.cert = %v\n", p.Cert)
		fmt.Fprintf(&b, "tls.min-version = %v\n", p.MinVersion)
	}
	return b.String()
}
