// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type rNestedShadow struct {
	Leaf *string `json:"leaf" toml:"leaf" yaml:"leaf"`
}

type rOptShadow struct {
	Leaf  *string `json:"leaf"  toml:"leaf"  yaml:"leaf"`
	Other *string `json:"other" toml:"other" yaml:"other"`
}

type requiredShadow struct {
	Top    *string        `json:"top"    toml:"top"    yaml:"top"`
	Nested *rNestedShadow `json:"nested" toml:"nested" yaml:"nested"`
	Opt    *rOptShadow    `json:"opt"    toml:"opt"    yaml:"opt"`
	Items  *[]rOptShadow  `json:"items"  toml:"items"  yaml:"items"`
}

func requiredConditionalRequired(cfg *Required) []string {
	var req []string
	if p := cfg.Opt; p != nil {
		req = append(req, "opt.leaf")
	}
	for ri := range cfg.Items {
		rp := "items[" + strconv.Itoa(ri) + "]"
		req = append(req, rp+".leaf")
	}
	return req
}

// RequiredSchema returns the generated schema for Required.
func RequiredSchema() *configulator.Schema[Required] {
	return &configulator.Schema[Required]{
		ApplyDefaults:       requiredApplyDefaults,
		ApplyEnv:            requiredApplyEnv,
		ConditionalRequired: requiredConditionalRequired,
		DecodeFile:          requiredDecodeFile,
		Required:            []string{"top", "nested.leaf"},
	}
}

func requiredApplyDefaults(_ *Required, _ string, _ configulator.SetOrigin) error {
	return nil
}

func requiredDecodeFile(data []byte, u configulator.Unmarshal, cfg *Required, sep string, set configulator.SetOrigin, file string) error {
	var sh requiredShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *requiredShadow) applyTo(cfg *Required, _ string, set configulator.SetOrigin, file string) error {
	if s.Top != nil {
		cfg.Top = *s.Top
		set("top", configulator.LayerFile, file)
	}
	if s.Nested != nil {
		if s.Nested.Leaf != nil {
			cfg.Nested.Leaf = *s.Nested.Leaf
			set("nested.leaf", configulator.LayerFile, file)
		}
	}
	if s.Opt != nil {
		e := ROpt{}
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		if s.Opt.Leaf != nil {
			e.Leaf = *s.Opt.Leaf
			set("opt.leaf", configulator.LayerFile, file)
		}
		if s.Opt.Other != nil {
			e.Other = *s.Opt.Other
			set("opt.other", configulator.LayerFile, file)
		}
		cfg.Opt = &e
	}
	if s.Items != nil {
		out := make([]ROpt, len(*s.Items))
		for i, esh := range *s.Items {
			var e ROpt
			idx := "items[" + strconv.Itoa(i) + "]"
			if esh.Leaf != nil {
				e.Leaf = *esh.Leaf
				set(idx+".leaf", configulator.LayerFile, file)
			}
			if esh.Other != nil {
				e.Other = *esh.Other
				set(idx+".other", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.Items = out
		set("items", configulator.LayerFile, file)
	}
	return nil
}

func requiredApplyEnv(cfg *Required, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "top"); ok {
		cfg.Top = v
		set("top", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nested", "leaf"); ok {
		cfg.Nested.Leaf = v
		set("nested.leaf", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "opt", "leaf"); ok {
		var e ROpt
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		e.Leaf = v
		cfg.Opt = &e
		set("opt.leaf", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "opt", "other"); ok {
		var e ROpt
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		e.Other = v
		cfg.Opt = &e
		set("opt.other", configulator.LayerEnv, n)
	}
	return nil
}

// RequiredPFlagHooks returns the pflag hooks for Required.
func RequiredPFlagHooks() cpflag.Hooks[Required] {
	return cpflag.Hooks[Required]{
		Apply:    requiredApplyPFlags,
		Register: requiredRegisterPFlags,
	}
}

func requiredRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"top",
		"nested" + o.Separator + "leaf",
		"opt" + o.Separator + "leaf",
		"opt" + o.Separator + "other",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "", "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.String(names[3], "", "")
	return nil
}

func requiredApplyPFlags(cfg *Required, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "top"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "top",
				Source: "--" + n,
			}
		}
		cfg.Top = v
		set("top", configulator.LayerCLI, "--"+n)
	}
	if n := "nested" + o.Separator + "leaf"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nested.leaf",
				Source: "--" + n,
			}
		}
		cfg.Nested.Leaf = v
		set("nested.leaf", configulator.LayerCLI, "--"+n)
	}
	if n := "opt" + o.Separator + "leaf"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "opt.leaf",
				Source: "--" + n,
			}
		}
		var e ROpt
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		e.Leaf = v
		cfg.Opt = &e
		set("opt.leaf", configulator.LayerCLI, "--"+n)
	}
	if n := "opt" + o.Separator + "other"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "opt.other",
				Source: "--" + n,
			}
		}
		var e ROpt
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		e.Other = v
		cfg.Opt = &e
		set("opt.other", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *requiredShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "top":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Top = &str
			default:
				return requiredJSONError("top", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "nested":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return requiredJSONError("nested", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub rNestedShadow
				if err := sub.decodeJSON(dec, "nested"); err != nil {
					return err
				}
				s.Nested = &sub
			}
		case "opt":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return requiredJSONError("opt", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub rOptShadow
				if err := sub.decodeJSON(dec, "opt"); err != nil {
					return err
				}
				s.Opt = &sub
			}
		case "items":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return requiredJSONError("items", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []rOptShadow{}
				for dec.PeekKind() != jsontext.KindEndArray {
					ep := "items" + "[" + strconv.Itoa(len(out)) + "]"
					et, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if et.Kind() != jsontext.KindBeginObject {
						return requiredJSONError(ep, et, fmt.Errorf("expected an object, got %v", et.Kind()))
					}
					var el rOptShadow
					if err := el.decodeJSON(dec, ep); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Items = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: requiredQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*requiredShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *rNestedShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "leaf":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Leaf = &str
			default:
				return requiredJSONError(path+".leaf", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + requiredQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *rOptShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "leaf":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Leaf = &str
			default:
				return requiredJSONError(path+".leaf", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "other":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Other = &str
			default:
				return requiredJSONError(path+".other", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + requiredQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// requiredJSONError returns a ParseError for the JSON token v at path.
func requiredJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Required) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "top = %v\n", c.Top)
	fmt.Fprintf(&b, "nested.leaf = %v\n", c.Nested.Leaf)
	if p := c.Opt; p == nil {
		b.WriteString("opt = <unset>\n")
	} else {
		fmt.Fprintf(&b, "opt.leaf = %v\n", p.Leaf)
		fmt.Fprintf(&b, "opt.other = %v\n", p.Other)
	}
	fmt.Fprintf(&b, "items = %v\n", c.Items)
	return b.String()
}

func requiredQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
