// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
)

type rNestedShadow struct {
	Leaf *string `json:"leaf" toml:"leaf" yaml:"leaf"`
}

type rOptShadow struct {
	Leaf  *string `json:"leaf" toml:"leaf" yaml:"leaf"`
	Other *string `json:"other" toml:"other" yaml:"other"`
}

type requiredShadow struct {
	Top    *string        `json:"top" toml:"top" yaml:"top"`
	Nested *rNestedShadow `json:"nested" toml:"nested" yaml:"nested"`
	Opt    *rOptShadow    `json:"opt" toml:"opt" yaml:"opt"`
	Items  *[]rOptShadow  `json:"items" toml:"items" yaml:"items"`
}

func requiredConditionalRequired(cfg *Required) []string {
	var req []string
	if p := cfg.Opt; p != nil {
		req = append(req, "opt.leaf")
	}
	for ri := range cfg.Items {
		rp := "items[" + strconv.Itoa(ri) + "]"
		req = append(req, rp+".leaf")
	}
	return req
}

// RequiredSchema returns the generated schema for Required.
func RequiredSchema() *configulator.Schema[Required] {
	return &configulator.Schema[Required]{
		ApplyDefaults:       requiredApplyDefaults,
		ApplyEnv:            requiredApplyEnv,
		ConditionalRequired: requiredConditionalRequired,
		DecodeFile:          requiredDecodeFile,
		Required:            []string{"top", "nested.leaf"},
	}
}

func requiredApplyDefaults(cfg *Required, sep string, set configulator.SetOrigin) error {
	return nil
}

func requiredDecodeFile(data []byte, u configulator.Unmarshal, cfg *Required, sep string, set configulator.SetOrigin, file string) error {
	var sh requiredShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *requiredShadow) applyTo(cfg *Required, sep string, set configulator.SetOrigin, file string) error {
	if s.Top != nil {
		cfg.Top = *s.Top
		set("top", configulator.LayerFile, file)
	}
	if s.Nested != nil {
		if s.Nested.Leaf != nil {
			cfg.Nested.Leaf = *s.Nested.Leaf
			set("nested.leaf", configulator.LayerFile, file)
		}
	}
	if s.Opt != nil {
		e := ROpt{}
		if cfg.Opt != nil {
			e = *cfg.Opt
		}
		if s.Opt.Leaf != nil {
			e.Leaf = *s.Opt.Leaf
			set("opt.leaf", configulator.LayerFile, file)
		}
		if s.Opt.Other != nil {
			e.Other = *s.Opt.Other
			set("opt.other", configulator.LayerFile, file)
		}
		cfg.Opt = &e
	}
	if s.Items != nil {
		out := make([]ROpt, len(*s.Items))
		for i, esh := range *s.Items {
			var e ROpt
			idx := "items[" + strconv.Itoa(i) + "]"
			if esh.Leaf != nil {
				e.Leaf = *esh.Leaf
				set(idx+".leaf", configulator.LayerFile, file)
			}
			if esh.Other != nil {
				e.Other = *esh.Other
				set(idx+".other", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.Items = out
		set("items", configulator.LayerFile, file)
	}
	return nil
}

func requiredApplyEnv(cfg *Required, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("top"); ok {
		cfg.Top = v
		set("top", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("nested", "leaf"); ok {
		cfg.Nested.Leaf = v
		set("nested.leaf", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("opt", "leaf"); ok {
		{
			var e ROpt
			if cfg.Opt != nil {
				e = *cfg.Opt
			} else {
			}
			e.Leaf = v
			cfg.Opt = &e
		}
		set("opt.leaf", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("opt", "other"); ok {
		{
			var e ROpt
			if cfg.Opt != nil {
				e = *cfg.Opt
			} else {
			}
			e.Other = v
			cfg.Opt = &e
		}
		set("opt.other", configulator.LayerEnv, n)
	}
	return nil
}

// RequiredPFlagHooks returns the pflag hooks for Required.
func RequiredPFlagHooks() cpflag.Hooks[Required] {
	return cpflag.Hooks[Required]{
		Apply:    requiredApplyPFlags,
		Register: requiredRegisterPFlags,
	}
}

func requiredRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"top",
		"nested" + o.Separator + "leaf",
		"opt" + o.Separator + "leaf",
		"opt" + o.Separator + "other",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "", "")
	fs.String(names[1], "", "")
	fs.String(names[2], "", "")
	fs.String(names[3], "", "")
	return nil
}

func requiredApplyPFlags(cfg *Required, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := "top"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "top",
				Source: "--" + n,
			}
		}
		cfg.Top = v
		set("top", configulator.LayerCLI, "--"+n)
	}
	if n := "nested" + o.Separator + "leaf"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nested.leaf",
				Source: "--" + n,
			}
		}
		cfg.Nested.Leaf = v
		set("nested.leaf", configulator.LayerCLI, "--"+n)
	}
	if n := "opt" + o.Separator + "leaf"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "opt.leaf",
				Source: "--" + n,
			}
		}
		{
			var e ROpt
			if cfg.Opt != nil {
				e = *cfg.Opt
			} else {
			}
			e.Leaf = v
			cfg.Opt = &e
		}
		set("opt.leaf", configulator.LayerCLI, "--"+n)
	}
	if n := "opt" + o.Separator + "other"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "opt.other",
				Source: "--" + n,
			}
		}
		{
			var e ROpt
			if cfg.Opt != nil {
				e = *cfg.Opt
			} else {
			}
			e.Other = v
			cfg.Opt = &e
		}
		set("opt.other", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *requiredShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "top":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Top = &str
			default:
				return fmt.Errorf("top: expected a string, got %v", v.Kind())
			}
		case "nested":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub rNestedShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Nested = &sub
			}
		case "opt":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub rOptShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Opt = &sub
			}
		case "items":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("items: expected an array, got %v", tok.Kind())
				}
				out := []rOptShadow{}
				for dec.PeekKind() != ']' {
					var el rOptShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Items = &out
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*requiredShadow)(nil)

func (s *rNestedShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "leaf":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Leaf = &str
			default:
				return fmt.Errorf("leaf: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*rNestedShadow)(nil)

func (s *rOptShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "leaf":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Leaf = &str
			default:
				return fmt.Errorf("leaf: expected a string, got %v", v.Kind())
			}
		case "other":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Other = &str
			default:
				return fmt.Errorf("other: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ json.UnmarshalerFrom = (*rOptShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Required) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "top = %v\n", c.Top)
	fmt.Fprintf(&b, "nested.leaf = %v\n", c.Nested.Leaf)
	if p := c.Opt; p == nil {
		b.WriteString("opt = <unset>\n")
	} else {
		fmt.Fprintf(&b, "opt.leaf = %v\n", p.Leaf)
		fmt.Fprintf(&b, "opt.other = %v\n", p.Other)
	}
	fmt.Fprintf(&b, "items = %v\n", c.Items)
	return b.String()
}
