// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
)

type scalarsShadow struct {
	Name    *string  `json:"name"    toml:"name"    yaml:"name"`
	Count   *int64   `json:"count"   toml:"count"   yaml:"count"`
	Port    *uint16  `json:"port"    toml:"port"    yaml:"port"`
	Ratio   *float64 `json:"ratio"   toml:"ratio"   yaml:"ratio"`
	Verbose *bool    `json:"verbose" toml:"verbose" yaml:"verbose"`
}

// ScalarsSchema returns the generated schema for Scalars.
func ScalarsSchema() *configulator.Schema[Scalars] {
	return &configulator.Schema[Scalars]{
		ApplyDefaults: scalarsApplyDefaults,
		ApplyEnv:      scalarsApplyEnv,
		DecodeFile:    scalarsDecodeFile,
	}
}

func scalarsApplyDefaults(cfg *Scalars, _ string, set configulator.SetOrigin) error {
	cfg.Name = "svc"
	set("name", configulator.LayerDefault, "default tag")
	cfg.Port = uint16(8080)
	set("port", configulator.LayerDefault, "default tag")
	cfg.Ratio = 1.5
	set("ratio", configulator.LayerDefault, "default tag")
	cfg.Verbose = false
	set("verbose", configulator.LayerDefault, "default tag")
	return nil
}

func scalarsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Scalars, sep string, set configulator.SetOrigin, file string) error {
	var sh scalarsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *scalarsShadow) applyTo(cfg *Scalars, _ string, set configulator.SetOrigin, file string) error {
	if s.Name != nil {
		cfg.Name = *s.Name
		set("name", configulator.LayerFile, file)
	}
	if s.Count != nil {
		cfg.Count = *s.Count
		set("count", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.Ratio != nil {
		cfg.Ratio = *s.Ratio
		set("ratio", configulator.LayerFile, file)
	}
	if s.Verbose != nil {
		cfg.Verbose = *s.Verbose
		set("verbose", configulator.LayerFile, file)
	}
	return nil
}

func scalarsApplyEnv(cfg *Scalars, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := ec.Lookup("name"); ok {
		cfg.Name = v
		set("name", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("count"); ok {
		p, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "count",
				Source: n,
				Value:  v,
			}
		}
		cfg.Count = p
		set("count", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = uint16(p)
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("ratio"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ratio",
				Source: n,
				Value:  v,
			}
		}
		cfg.Ratio = p
		set("ratio", configulator.LayerEnv, n)
	}
	if n, v, ok := ec.Lookup("verbose"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "verbose",
				Source: n,
				Value:  v,
			}
		}
		cfg.Verbose = p
		set("verbose", configulator.LayerEnv, n)
	}
	return nil
}

// ScalarsPFlagHooks returns the pflag hooks for Scalars.
func ScalarsPFlagHooks() cpflag.Hooks[Scalars] {
	return cpflag.Hooks[Scalars]{
		Apply:    scalarsApplyPFlags,
		Register: scalarsRegisterPFlags,
	}
}

func scalarsRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"name",
		"count",
		"port",
		"ratio",
		"verbose",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "svc", "")
	fs.Int64(names[1], 0, "")
	fs.Uint16(names[2], 8080, "")
	fs.Float64(names[3], 1.5, "")
	fs.Bool(names[4], false, "")
	return nil
}

func scalarsApplyPFlags(cfg *Scalars, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "name",
				Source: "--" + n,
			}
		}
		cfg.Name = v
		set("name", configulator.LayerCLI, "--"+n)
	}
	if n := "count"; fs.Changed(n) {
		v, err := fs.GetInt64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "count",
				Source: "--" + n,
			}
		}
		cfg.Count = v
		set("count", configulator.LayerCLI, "--"+n)
	}
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := "ratio"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ratio",
				Source: "--" + n,
			}
		}
		cfg.Ratio = v
		set("ratio", configulator.LayerCLI, "--"+n)
	}
	if n := "verbose"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "verbose",
				Source: "--" + n,
			}
		}
		cfg.Verbose = v
		set("verbose", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *scalarsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch tok.String() {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "count":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Int()
				if err != nil {
					return fmt.Errorf("count: %w", err)
				}
				val := num
				s.Count = &val
			default:
				return fmt.Errorf("count: expected a number, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Uint()
				if err != nil {
					return fmt.Errorf("port: %w", err)
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "ratio":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return fmt.Errorf("ratio: %w", err)
				}
				val := num
				s.Ratio = &val
			default:
				return fmt.Errorf("ratio: expected a number, got %v", v.Kind())
			}
		case "verbose":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Verbose = &b
			default:
				return fmt.Errorf("verbose: expected a bool, got %v", v.Kind())
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return fmt.Errorf("unknown key %q", tok.String())
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*scalarsShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Scalars) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "name = %v\n", c.Name)
	fmt.Fprintf(&b, "count = %v\n", c.Count)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	fmt.Fprintf(&b, "ratio = %v\n", c.Ratio)
	fmt.Fprintf(&b, "verbose = %v\n", c.Verbose)
	return b.String()
}
