// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package conformance

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"strconv"
	"strings"
)

type scalarsShadow struct {
	Name    *string  `json:"name" toml:"name" yaml:"name"`
	Count   *int64   `json:"count" toml:"count" yaml:"count"`
	Port    *uint16  `json:"port" toml:"port" yaml:"port"`
	Ratio   *float64 `json:"ratio" toml:"ratio" yaml:"ratio"`
	Verbose *bool    `json:"verbose" toml:"verbose" yaml:"verbose"`
}

// ScalarsSchema returns the generated schema for Scalars.
func ScalarsSchema() *configulator.Schema[Scalars] {
	return &configulator.Schema[Scalars]{
		ApplyDefaults: scalarsApplyDefaults,
		ApplyEnv:      scalarsApplyEnv,
		DecodeFile:    scalarsDecodeFile,
	}
}
func scalarsApplyDefaults(cfg *Scalars, set configulator.SetOrigin) error {
	cfg.Name = "svc"
	set("name", configulator.LayerDefault, "default tag")
	cfg.Port = uint16(8080)
	set("port", configulator.LayerDefault, "default tag")
	cfg.Ratio = 1.5
	set("ratio", configulator.LayerDefault, "default tag")
	cfg.Verbose = false
	set("verbose", configulator.LayerDefault, "default tag")
	return nil
}
func scalarsDecodeFile(data []byte, u configulator.Unmarshal, cfg *Scalars, set configulator.SetOrigin, file string) error {
	var sh scalarsShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *scalarsShadow) applyTo(cfg *Scalars, set configulator.SetOrigin, file string) error {
	if s.Name != nil {
		cfg.Name = *s.Name
		set("name", configulator.LayerFile, file)
	}
	if s.Count != nil {
		cfg.Count = *s.Count
		set("count", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.Ratio != nil {
		cfg.Ratio = *s.Ratio
		set("ratio", configulator.LayerFile, file)
	}
	if s.Verbose != nil {
		cfg.Verbose = *s.Verbose
		set("verbose", configulator.LayerFile, file)
	}
	return nil
}
func scalarsApplyEnv(cfg *Scalars, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "name"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Name = v
			set("name", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "count"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "count",
					Source: n,
					Value:  v,
				}
			}
			cfg.Count = p
			set("count", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Port = uint16(p)
			set("port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ratio"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "ratio",
					Source: n,
					Value:  v,
				}
			}
			cfg.Ratio = p
			set("ratio", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "verbose"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "verbose",
					Source: n,
					Value:  v,
				}
			}
			cfg.Verbose = p
			set("verbose", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ScalarsPFlagHooks returns the pflag hooks for Scalars.
func ScalarsPFlagHooks() cpflag.Hooks[Scalars] {
	return cpflag.Hooks[Scalars]{
		Apply:    scalarsApplyPFlags,
		Register: scalarsRegisterPFlags,
	}
}
func scalarsRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"name"}, o.Separator), strings.Join([]string{"count"}, o.Separator), strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"ratio"}, o.Separator), strings.Join([]string{"verbose"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"name"}, o.Separator), "svc", "")
	fs.Int64(strings.Join([]string{"count"}, o.Separator), int64(0), "")
	fs.Uint16(strings.Join([]string{"port"}, o.Separator), uint16(8080), "")
	fs.Float64(strings.Join([]string{"ratio"}, o.Separator), 1.5, "")
	fs.Bool(strings.Join([]string{"verbose"}, o.Separator), false, "")
	return nil
}
func scalarsApplyPFlags(cfg *Scalars, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "name",
				Source: "--" + n,
			}
		}
		cfg.Name = v
		set("name", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"count"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "count",
				Source: "--" + n,
			}
		}
		cfg.Count = v
		set("count", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ratio"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ratio",
				Source: "--" + n,
			}
		}
		cfg.Ratio = v
		set("ratio", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"verbose"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "verbose",
				Source: "--" + n,
			}
		}
		cfg.Verbose = v
		set("verbose", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *scalarsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "count":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := num
				s.Count = &val
			default:
				return fmt.Errorf("count: expected a number, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "ratio":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Ratio = &val
			default:
				return fmt.Errorf("ratio: expected a number, got %v", v.Kind())
			}
		case "verbose":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Verbose = &b
			default:
				return fmt.Errorf("verbose: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*scalarsShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". Values never appear in the origin
// Report; this method is the one place redaction is enforced.
func (c *Scalars) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("name = %v\n", c.Name))
	b.WriteString(fmt.Sprintf("count = %v\n", c.Count))
	b.WriteString(fmt.Sprintf("port = %v\n", c.Port))
	b.WriteString(fmt.Sprintf("ratio = %v\n", c.Ratio))
	b.WriteString(fmt.Sprintf("verbose = %v\n", c.Verbose))
	return b.String()
}
